export const dummyData = [
  {
    _id: 'a7ecc543-61ae-455e-9d6c-bc5f2eae217e',
    name: 'Foldable Dining Set',
    price: 291.77,
    discount: null,
    stock: 14,
    description:
      'Space-saving dining set perfect for small apartments with smooth folding mechanism and sturdy construction.',
    dimensions: { height: '53cm', width: '85cm', depth: '72cm' },
    material: 'wood',
    colors: [
      {
        name: 'Cherry',
        hex: '#D5A372',
        image: 'https://hogfurniture.co/cdn/shop/articles/Home_collection.png?v=1657288179',
      },
      { name: 'Burgundy', hex: '#800020', image: '/images/image-placeholder.png' },
      { name: 'White', hex: '#FFFFFF', image: '/images/image-placeholder.png' },
      { name: 'Pine', hex: '#2A2F23', image: '/images/image-placeholder.png' },
    ],
    image: 'https://hogfurniture.co/cdn/shop/articles/Home_collection.png?v=1657288179',
    ratings: 4.3,
    reviews: [
      {
        user: 'Jamill Tonsley',
        comment: 'Perfect for our tiny kitchen! Easy to set up and looks beautiful with the cherry finish.',
        rating: 4.3,
      },
    ],
    tags: ['dining', 'space-saving', 'wooden', 'compact', 'apartment-friendly'],
    shippingInfo: { weight: 142.61, deliveryTime: '7-13 days' },
    warranty: null,
    returnPolicy: '30-day return',
  },
  {
    _id: 'd8098e99-e200-400a-bc05-11f1d9102991',
    name: 'Adjustable Bookshelf',
    price: 618.48,
    discount: 29,
    stock: 9,
    description: 'Customizable shelving unit with modular design to fit any space and book collection.',
    dimensions: { height: '185cm', width: '113cm', depth: '26cm' },
    material: 'metal',
    colors: [
      {
        name: 'Green',
        hex: '#008000',
        image:
          'https://hips.hearstapps.com/hmg-prod/images/81dhypy18rl-ac-sl1500-1671477754.jpg?crop=1xw:1xh;center,top&resize=980:*',
      },
      { name: 'Maroon', hex: '#800000', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://hips.hearstapps.com/hmg-prod/images/81dhypy18rl-ac-sl1500-1671477754.jpg?crop=1xw:1xh;center,top&resize=980:*',
    ratings: 1.8,
    reviews: [
      {
        user: 'Trixi Lowne',
        comment: 'Shelves arrived scratched and the assembly instructions were unclear. Disappointing quality.',
        rating: 1.8,
      },
    ],
    tags: ['bookshelf', 'adjustable', 'storage', 'office', 'study'],
    shippingInfo: { weight: 166.79, deliveryTime: '9-12 days' },
    warranty: null,
    returnPolicy: null,
  },
  {
    _id: '29e0211c-6dbb-413c-b322-ab51d707842d',
    name: 'Plastic Storage Shelf',
    price: 471.79,
    discount: null,
    stock: 17,
    description: 'Lightweight and durable plastic shelving unit ideal for garages or utility rooms.',
    dimensions: { height: '88cm', width: '54cm', depth: '76cm' },
    material: 'plastic',
    colors: [
      {
        name: 'Pine',
        hex: '#2A2F23',
        image: 'https://anufurnitures.com/wp-content/uploads/2023/07/AdobeStock_191423292-scaled.jpeg.webp',
      },
      { name: 'Rose Gold', hex: '#B76E79', image: '/images/image-placeholder.png' },
    ],
    image: 'https://anufurnitures.com/wp-content/uploads/2023/07/AdobeStock_191423292-scaled.jpeg.webp',
    ratings: 2.7,
    reviews: [
      {
        user: 'Joshua Thomann',
        comment: 'Does the job but feels a bit flimsy. Good for light storage.',
        rating: 2.7,
      },
    ],
    tags: ['storage', 'utility', 'garage', 'lightweight', 'budget'],
    shippingInfo: { weight: 43.58, deliveryTime: '3-6 days' },
    warranty: null,
    returnPolicy: null,
  },
  {
    _id: '69e2014d-44a2-488a-92ac-ea8af0999197',
    name: 'Rolling Filing Cabinet',
    price: 672.14,
    discount: null,
    stock: null,
    description: 'Sleek mobile filing system with smooth-rolling casters and secure document storage.',
    dimensions: { height: '95cm', width: '42cm', depth: '30cm' },
    material: 'metal',
    colors: [
      {
        name: 'Maroon',
        hex: '#800000',
        image: 'https://affordableluxuryfurniture.ie/wp-content/uploads/2022/03/Kayla-Viola-Midnight.jpg',
      },
      { name: 'Off-White', hex: '#FAF9F6', image: '/images/image-placeholder.png' },
      { name: 'Walnut', hex: '#5C4033', image: '/images/image-placeholder.png' },
      { name: 'Lilac', hex: '#C8A2C8', image: '/images/image-placeholder.png' },
    ],
    image: 'https://affordableluxuryfurniture.ie/wp-content/uploads/2022/03/Kayla-Viola-Midnight.jpg',
    ratings: 0,
    reviews: [],
    tags: ['office', 'filing', 'mobile', 'storage', 'professional'],
    shippingInfo: { weight: 143.0, deliveryTime: '4-13 days' },
    warranty: '3 years',
    returnPolicy: null,
  },
  {
    _id: 'acc9311f-f98a-48e3-994e-5d27f06bc8ff',
    name: 'Contemporary Bookshelf',
    price: 812.54,
    discount: 18,
    stock: null,
    description: 'Modern bookshelf with asymmetrical design that adds artistic flair to any room.',
    dimensions: { height: '69cm', width: '58cm', depth: '61cm' },
    material: 'wood',
    colors: [
      {
        name: 'Turquoise',
        hex: '#40E0D0',
        image:
          'https://www.realsimple.com/thmb/kRRAaK6XhZIqL_GFIxfZzHTHx7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/furniture-styles-GettyImages-1467984982-512fed4077b646eabbc187619554d517.jpg',
      },
      { name: 'Maroon', hex: '#800000', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://www.realsimple.com/thmb/kRRAaK6XhZIqL_GFIxfZzHTHx7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/furniture-styles-GettyImages-1467984982-512fed4077b646eabbc187619554d517.jpg',
    ratings: 3.0,
    reviews: [
      {
        user: 'Conny Rowlatt',
        comment: "Unique design but the shelves aren't very sturdy. Books keep sliding.",
        rating: 2.0,
      },
      {
        user: 'Gib Peele',
        comment: 'Beautiful statement piece for our living room. Gets lots of compliments.',
        rating: 4.7,
      },
      {
        user: 'Timmy Tills',
        comment: 'Excellent craftsmanship and the perfect size for our collection.',
        rating: 4.5,
      },
      {
        user: 'Noelyn Clayson',
        comment: 'Arrived with minor scratches but otherwise good quality.',
        rating: 2.1,
      },
    ],
    tags: ['modern', 'designer', 'living-room', 'decor', 'statement-piece'],
    shippingInfo: { weight: 146.35, deliveryTime: '2-14 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
  },
  {
    _id: 'ccc18f50-9dec-43c5-8b8f-f1d125f22c97',
    name: 'Waterproof Patio Bench',
    price: 83.75,
    discount: null,
    stock: 20,
    description: 'Weather-resistant outdoor seating with comfortable slatted design and powder-coated frame.',
    dimensions: { height: '45cm', width: '120cm', depth: '40cm' },
    material: 'plastic',
    colors: [
      {
        name: 'Ash',
        hex: '#B2BEB5',
        image:
          'https://img.freepik.com/premium-photo/yellow-sofa-home-office-furniture-white-clear-surface-png-transparent-background_94628-30183.jpg',
      },
      { name: 'Pink', hex: '#FFC0CB', image: '/images/image-placeholder.png' },
      { name: 'Purple', hex: '#800080', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://img.freepik.com/premium-photo/yellow-sofa-home-office-furniture-white-clear-surface-png-transparent-background_94628-30183.jpg',
    ratings: 3.3,
    reviews: [
      {
        user: 'Peder Rable',
        comment: 'Great value for money. Withstood heavy rain without any issues.',
        rating: 3.4,
      },
      {
        user: 'Duncan Swyer-Sexey',
        comment: 'Not as comfortable as expected. The plastic gets very hot in direct sun.',
        rating: 1.8,
      },
      {
        user: 'Missy De Biasi',
        comment: 'Perfect size for our small balcony. Easy to clean.',
        rating: 2.0,
      },
    ],
    tags: ['outdoor', 'patio', 'garden', 'weatherproof', 'affordable'],
    shippingInfo: { weight: 69.35, deliveryTime: '4-8 days' },
    warranty: null,
    returnPolicy: null,
  },
  {
    _id: '08ed90d8-d938-4c56-b18a-dc09364a8223',
    name: 'Elegant Ottoman',
    price: 425.8,
    discount: 8,
    stock: 19,
    description: 'Versatile upholstered ottoman with hidden storage compartment and tufted top.',
    dimensions: { height: '46cm', width: '70cm', depth: '60cm' },
    material: 'fabric',
    colors: [
      {
        name: 'Rose Gold',
        hex: '#B76E79',
        image:
          'https://cityfurnish.com/blog/wp-content/uploads/2024/02/alexa-6-seater-dining-table-with-4-chairs-and-bench-1-1694416018.webp',
      },
    ],
    image:
      'https://cityfurnish.com/blog/wp-content/uploads/2024/02/alexa-6-seater-dining-table-with-4-chairs-and-bench-1-1694416018.webp',
    ratings: 1.5,
    reviews: [
      {
        user: 'Mahmud Huyton',
        comment: 'Fabric stains easily and the storage space is smaller than advertised.',
        rating: 2.8,
      },
      {
        user: 'Nonie Whiff',
        comment: 'Comfortable footrest and matches our decor perfectly.',
        rating: 3.4,
      },
      {
        user: 'Sean Tunney',
        comment: 'Excellent quality and the rose gold finish is stunning.',
        rating: 4.6,
      },
      {
        user: 'Mignonne Fairebrother',
        comment: 'Legs arrived wobbly and the fabric has loose threads.',
        rating: 1.5,
      },
      {
        user: 'Dorrie Olensby',
        comment: 'Perfect addition to our living room. Very sturdy and stylish.',
        rating: 4.8,
      },
    ],
    tags: ['living-room', 'storage', 'footrest', 'decor', 'multifunctional'],
    shippingInfo: { weight: 194.81, deliveryTime: '12-14 days' },
    warranty: null,
    returnPolicy: '30-day return',
  },
  {
    _id: '421711c0-f53f-452a-b332-72358069b7a3',
    name: 'Fire Pit Dining Set',
    price: 620.54,
    discount: 6,
    stock: 18,
    description: 'Complete outdoor dining experience with built-in fire pit and comfortable seating.',
    dimensions: { height: '75cm', width: '150cm', depth: '150cm' },
    material: 'metal',
    colors: [
      {
        name: 'Brown',
        hex: '#964B00',
        image: 'https://www.lifestylefurnitureplus.com/wp-content/uploads/2023/08/960x860-Nolan-Nixon-003.png',
      },
      { name: 'Black', hex: '#000000', image: '/images/image-placeholder.png' },
      { name: 'Rose Gold', hex: '#B76E79', image: '/images/image-placeholder.png' },
      { name: 'Burgundy', hex: '#800020', image: '/images/image-placeholder.png' },
      { name: 'Sky Blue', hex: '#87CEEB', image: '/images/image-placeholder.png' },
    ],
    image: 'https://www.lifestylefurnitureplus.com/wp-content/uploads/2023/08/960x860-Nolan-Nixon-003.png',
    ratings: 4.0,
    reviews: [
      {
        user: 'Helenka Handsheart',
        comment: 'Perfect for evening gatherings. The fire pit works great.',
        rating: 3.5,
      },
      {
        user: 'Klemens Beldon',
        comment: 'Assembly was challenging but the end result is beautiful.',
        rating: 2.0,
      },
    ],
    tags: ['outdoor', 'dining', 'fire-pit', 'patio', 'entertaining'],
    shippingInfo: { weight: 47.89, deliveryTime: '5-12 days' },
    warranty: null,
    returnPolicy: null,
  },
  {
    _id: '585c4aaa-e0e2-4939-a8b4-c0915eb0e610',
    name: 'Deluxe Velvet Sofa',
    price: 668.76,
    discount: 15,
    stock: null,
    description: 'Plush velvet sofa with deep seating and elegant tapered legs for a luxurious look.',
    dimensions: { height: '85cm', width: '210cm', depth: '95cm' },
    material: 'wood',
    colors: [
      {
        name: 'Forest Green',
        hex: '#228B22',
        image:
          'https://homelinefurniture.ie/media/catalog/product/cache/4333fa618451a5190449de1dd5eb7f37/6/2/62725.jpeg',
      },
    ],
    image: 'https://homelinefurniture.ie/media/catalog/product/cache/4333fa618451a5190449de1dd5eb7f37/6/2/62725.jpeg',
    ratings: 4.2,
    reviews: [
      {
        user: 'Rufus Synan',
        comment: 'Color is beautiful but the cushions flatten quickly.',
        rating: 1.3,
      },
      {
        user: 'Eva Huckett',
        comment: 'Extremely comfortable and the velvet is high quality.',
        rating: 3.8,
      },
      {
        user: 'Morgun Beaulieu',
        comment: 'Perfect centerpiece for our living room. Worth every penny.',
        rating: 4.1,
      },
      {
        user: 'Norah Bynert',
        comment: 'Delivery was delayed but the sofa itself is gorgeous.',
        rating: 3.0,
      },
      {
        user: 'Myriam Bertin',
        comment: 'The forest green color is even more beautiful in person.',
        rating: 3.9,
      },
    ],
    tags: ['luxury', 'living-room', 'velvet', 'statement-piece', 'comfort'],
    shippingInfo: { weight: 89.36, deliveryTime: '2-12 days' },
    warranty: null,
    returnPolicy: null,
  },
  {
    _id: '24589f8e-a68d-47a7-9fe1-99309528facc',
    name: 'Compact Computer Desk',
    price: 848.24,
    discount: null,
    stock: 15,
    description: 'Ergonomic workspace solution with cable management and sturdy tempered glass top.',
    dimensions: { height: '75cm', width: '120cm', depth: '60cm' },
    material: 'glass',
    colors: [
      {
        name: 'Navy Blue',
        hex: '#000080',
        image:
          'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1678394427-screen-shot-2023-03-09-at-3-39-50-pm-640a441b4865a.png?crop=0.958xw:0.955xh;0.0144xw,0&resize=980:*',
      },
      { name: 'Blue', hex: '#0000FF', image: '/images/image-placeholder.png' },
      { name: 'Orange', hex: '#FFA500', image: '/images/image-placeholder.png' },
      { name: 'Black', hex: '#000000', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1678394427-screen-shot-2023-03-09-at-3-39-50-pm-640a441b4865a.png?crop=0.958xw:0.955xh;0.0144xw,0&resize=980:*',
    ratings: 4.7,
    reviews: [
      {
        user: 'Birch Leverington',
        comment: 'Perfect size for small spaces. The glass surface is easy to clean.',
        rating: 4.7,
      },
    ],
    tags: ['office', 'workspace', 'ergonomic', 'modern', 'home-office'],
    shippingInfo: { weight: 149.44, deliveryTime: '7-8 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
  },
  {
    _id: '6cbd6721-1c79-4208-91cf-65286fa4faaf',
    name: 'Luxe Velvet Sofa',
    price: 899,
    discount: null,
    stock: 8,
    description:
      'Indulgent comfort wrapped in luxurious velvet. This plush 3-seater features deep cushioning and sleek lines for a refined look that transforms any living space into a relaxing haven.',
    dimensions: { height: '85cm', width: '210cm', depth: '90cm' },
    material: 'velvet & hardwood',
    colors: [
      {
        name: 'Teal',
        hex: '#439792',
        image: '/images/luxe-velvet-teal.jpg',
      },
      { name: 'Rust Orange', hex: '#bf4b1c', image: '/images/luxe-velvet-orange.jpg' },
      { name: 'Caramel Brown', hex: '#c18f5b', image: '/images/luxe-velvet-brown.jpg' },
      { name: 'Light Blue', hex: '#abc3e9', image: '/images/luxe-velvet-light-blue.jpg' },
      { name: 'Sand', hex: '#c9bc90', image: '/images/luxe-velvet-sand.jpg' },
      { name: 'Gold', hex: '#dd9046', image: '/images/luxe-velvet-gold.jpg' },
    ],
    image: '/images/luxe-velvet-teal.jpg',
    ratings: 4.3,
    reviews: [
      {
        user: 'Claire Bennett',
        comment: 'Absolutely in love with the color and softness. Adds a luxe feel to my space.',
        rating: 4.9,
      },
      {
        user: 'Daniel Okafor',
        comment: 'The cushions are deep and plush. Ideal for lounging with family.',
        rating: 4.5,
      },
      {
        user: 'Amira El-Sayed',
        comment: 'Fabric is smooth and doesn’t trap pet hair. A great plus for pet owners.',
        rating: 4.2,
      },
      {
        user: 'Tobias Schmidt',
        comment: 'Setup took less than 15 minutes. Very impressed with the quality of materials.',
        rating: 4.4,
      },
      {
        user: 'Yumi Aoki',
        comment: 'Would love slightly firmer back support, but overall a gorgeous piece.',
        rating: 3.9,
      },
      {
        user: 'Marco De Luca',
        comment: 'Looks even better in person. The velvet has a rich texture under light.',
        rating: 4.8,
      },
      {
        user: 'Lina Novak',
        comment: 'My guests keep asking where I got it. Stylish and surprisingly affordable.',
        rating: 4.6,
      },
      {
        user: 'Aarav Mehta',
        comment: 'Comfortable to sit on for long hours. Great for movie nights.',
        rating: 4.1,
      },
      {
        user: 'Juliette Dubois',
        comment: 'Color matches the product photos perfectly. Delivery was quick too.',
        rating: 4.7,
      },
      {
        user: 'Oscar Thompson',
        comment: 'Minor wobble on one leg but easy to fix. Otherwise, very satisfied.',
        rating: 3.8,
      },
    ],
    tags: ['living-room', 'luxury', 'velvet', 'comfortable', 'sofa'],
    shippingInfo: { weight: 92.3, deliveryTime: '5-6 days' },
    warranty: '2 years',
    returnPolicy: '45-day return',
  },
];

export type ApplicationImageDataType = typeof ImageData;
