import { Product } from '../../types/chatbot';

export const dummyData: Product[] = [
  {
    _id: 'a7ecc543-61ae-455e-9d6c-bc5f2eae217e',
    name: 'Foldable Dining Set',
    arrivalDate: '2024-01-15',
    price: 291.77,
    discount: null,
    stock: 14,
    description:
      'Space-saving dining set perfect for small apartments with smooth folding mechanism and sturdy construction.',
    dimensions: { height: '53cm', width: '85cm', depth: '72cm' },
    size: 'medium',
    material: 'wood',
    category: 'Dining',
    status: ['top seller'],
    colors: [
      {
        name: 'Cherry',
        hex: '#D5A372',
        image: 'https://hogfurniture.co/cdn/shop/articles/Home_collection.png?v=1657288179',
      },
      { name: 'Burgundy', hex: '#800020', image: '/images/image-placeholder.png' },
      { name: 'White', hex: '#FFFFFF', image: '/images/image-placeholder.png' },
      { name: 'Pine', hex: '#2A2F23', image: '/images/image-placeholder.png' },
    ],
    image: 'https://hogfurniture.co/cdn/shop/articles/Home_collection.png?v=1657288179',
    ratings: 4.3,
    reviews: [
      {
        user: 'Jamill Tonsley',
        comment: 'Perfect for our tiny kitchen! Easy to set up and looks beautiful with the cherry finish.',
        rating: 4.3,
      },
    ],
    tags: ['dining', 'space-saving', 'wooden', 'compact', 'apartment-friendly'],
    shippingInfo: { weight: 142.61, deliveryTime: '7-13 days' },
    warranty: null,
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: 'd8098e99-e200-400a-bc05-11f1d9102991',
    name: 'Adjustable Bookshelf',
    arrivalDate: '2024-03-22',
    price: 618.48,
    discount: 29,
    stock: 9,
    description: 'Customizable shelving unit with modular design to fit any space and book collection.',
    dimensions: { height: '185cm', width: '113cm', depth: '26cm' },
    size: 'large',
    material: 'metal',
    category: 'Office Furniture',
    status: ['new arrival'],
    colors: [
      {
        name: 'Green',
        hex: '#008000',
        image:
          'https://hips.hearstapps.com/hmg-prod/images/81dhypy18rl-ac-sl1500-1671477754.jpg?crop=1xw:1xh;center,top&resize=980:*',
      },
      { name: 'Maroon', hex: '#800000', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://hips.hearstapps.com/hmg-prod/images/81dhypy18rl-ac-sl1500-1671477754.jpg?crop=1xw:1xh;center,top&resize=980:*',
    ratings: 1.8,
    reviews: [
      {
        user: 'Trixi Lowne',
        comment: 'Shelves arrived scratched and the assembly instructions were unclear. Disappointing quality.',
        rating: 1.8,
      },
    ],
    tags: ['bookshelf', 'adjustable', 'storage', 'office', 'study'],
    shippingInfo: { weight: 166.79, deliveryTime: '9-12 days' },
    warranty: null,
    returnPolicy: null,
    style: 'Industrial',
  },
  {
    _id: '29e0211c-6dbb-413c-b322-ab51d707842d',
    name: 'Plastic Storage Shelf',
    arrivalDate: '2023-11-10',
    price: 471.79,
    discount: null,
    stock: 17,
    description: 'Lightweight and durable plastic shelving unit ideal for garages or utility rooms.',
    dimensions: { height: '88cm', width: '54cm', depth: '76cm' },
    size: 'medium',
    material: 'plastic',
    category: 'Office Furniture',
    status: [],
    colors: [
      {
        name: 'Pine',
        hex: '#2A2F23',
        image: 'https://anufurnitures.com/wp-content/uploads/2023/07/AdobeStock_191423292-scaled.jpeg.webp',
      },
      { name: 'Rose Gold', hex: '#B76E79', image: '/images/image-placeholder.png' },
    ],
    image: 'https://anufurnitures.com/wp-content/uploads/2023/07/AdobeStock_191423292-scaled.jpeg.webp',
    ratings: 2.7,
    reviews: [
      {
        user: 'Joshua Thomann',
        comment: 'Does the job but feels a bit flimsy. Good for light storage.',
        rating: 2.7,
      },
    ],
    tags: ['storage', 'utility', 'garage', 'lightweight', 'budget'],
    shippingInfo: { weight: 43.58, deliveryTime: '3-6 days' },
    warranty: null,
    returnPolicy: null,
    style: 'Industrial',
  },
  {
    _id: '69e2014d-44a2-488a-92ac-ea8af0999197',
    name: 'Rolling Filing Cabinet',
    arrivalDate: '2024-04-05',
    price: 672.14,
    discount: null,
    stock: null,
    description: 'Sleek mobile filing system with smooth-rolling casters and secure document storage.',
    dimensions: { height: '95cm', width: '42cm', depth: '30cm' },
    size: 'small',
    material: 'metal',
    category: 'Office Furniture',
    status: ['new arrival'],
    colors: [
      {
        name: 'Maroon',
        hex: '#800000',
        image: 'https://affordableluxuryfurniture.ie/wp-content/uploads/2022/03/Kayla-Viola-Midnight.jpg',
      },
      { name: 'Off-White', hex: '#FAF9F6', image: '/images/image-placeholder.png' },
      { name: 'Walnut', hex: '#5C4033', image: '/images/image-placeholder.png' },
      { name: 'Lilac', hex: '#C8A2C8', image: '/images/image-placeholder.png' },
    ],
    image: 'https://affordableluxuryfurniture.ie/wp-content/uploads/2022/03/Kayla-Viola-Midnight.jpg',
    ratings: 0,
    reviews: [],
    tags: ['office', 'filing', 'mobile', 'storage', 'professional'],
    shippingInfo: { weight: 143.0, deliveryTime: '4-13 days' },
    warranty: '3 years',
    returnPolicy: null,
    style: 'Industrial',
  },
  {
    _id: 'acc9311f-f98a-48e3-994e-5d27f06bc8ff',
    name: 'Contemporary Bookshelf',
    arrivalDate: '2023-12-18',
    price: 812.54,
    discount: 18,
    stock: null,
    description: 'Modern bookshelf with asymmetrical design that adds artistic flair to any room.',
    dimensions: { height: '69cm', width: '58cm', depth: '61cm' },
    size: 'medium',
    material: 'wood',
    category: 'Living Room',
    status: ['top seller'],
    colors: [
      {
        name: 'Turquoise',
        hex: '#40E0D0',
        image:
          'https://www.realsimple.com/thmb/kRRAaK6XhZIqL_GFIxfZzHTHx7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/furniture-styles-GettyImages-1467984982-512fed4077b646eabbc187619554d517.jpg',
      },
      { name: 'Maroon', hex: '#800000', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://www.realsimple.com/thmb/kRRAaK6XhZIqL_GFIxfZzHTHx7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/furniture-styles-GettyImages-1467984982-512fed4077b646eabbc187619554d517.jpg',
    ratings: 3.0,
    reviews: [
      {
        user: 'Conny Rowlatt',
        comment: "Unique design but the shelves aren't very sturdy. Books keep sliding.",
        rating: 2.0,
      },
      {
        user: 'Gib Peele',
        comment: 'Beautiful statement piece for our living room. Gets lots of compliments.',
        rating: 4.7,
      },
      {
        user: 'Timmy Tills',
        comment: 'Excellent craftsmanship and the perfect size for our collection.',
        rating: 4.5,
      },
      {
        user: 'Noelyn Clayson',
        comment: 'Arrived with minor scratches but otherwise good quality.',
        rating: 2.1,
      },
    ],
    tags: ['modern', 'designer', 'living-room', 'decor', 'statement-piece'],
    shippingInfo: { weight: 146.35, deliveryTime: '2-14 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: 'ccc18f50-9dec-43c5-8b8f-f1d125f22c97',
    name: 'Waterproof Patio Bench',
    arrivalDate: '2024-02-28',
    price: 83.75,
    discount: null,
    stock: 20,
    description: 'Weather-resistant outdoor seating with comfortable slatted design and powder-coated frame.',
    dimensions: { height: '45cm', width: '120cm', depth: '40cm' },
    size: 'medium',
    material: 'plastic',
    category: 'Outdoor',
    status: ['top seller'],
    colors: [
      {
        name: 'Ash',
        hex: '#B2BEB5',
        image:
          'https://img.freepik.com/premium-photo/yellow-sofa-home-office-furniture-white-clear-surface-png-transparent-background_94628-30183.jpg',
      },
      { name: 'Pink', hex: '#FFC0CB', image: '/images/image-placeholder.png' },
      { name: 'Purple', hex: '#800080', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://img.freepik.com/premium-photo/yellow-sofa-home-office-furniture-white-clear-surface-png-transparent-background_94628-30183.jpg',
    ratings: 3.3,
    reviews: [
      {
        user: 'Peder Rable',
        comment: 'Great value for money. Withstood heavy rain without any issues.',
        rating: 3.4,
      },
      {
        user: 'Duncan Swyer-Sexey',
        comment: 'Not as comfortable as expected. The plastic gets very hot in direct sun.',
        rating: 1.8,
      },
      {
        user: 'Missy De Biasi',
        comment: 'Perfect size for our small balcony. Easy to clean.',
        rating: 2.0,
      },
    ],
    tags: ['outdoor', 'patio', 'garden', 'weatherproof', 'affordable'],
    shippingInfo: { weight: 69.35, deliveryTime: '4-8 days' },
    warranty: null,
    returnPolicy: null,
    style: 'Modern',
  },
  {
    _id: '08ed90d8-d938-4c56-b18a-dc09364a8223',
    name: 'Elegant Ottoman',
    arrivalDate: '2024-05-10',
    price: 425.8,
    discount: 8,
    stock: 19,
    description: 'Versatile upholstered ottoman with hidden storage compartment and tufted top.',
    dimensions: { height: '46cm', width: '70cm', depth: '60cm' },
    size: 'small',
    material: 'fabric',
    category: 'Living Room',
    status: ['new arrival'],
    colors: [
      {
        name: 'Rose Gold',
        hex: '#B76E79',
        image:
          'https://cityfurnish.com/blog/wp-content/uploads/2024/02/alexa-6-seater-dining-table-with-4-chairs-and-bench-1-1694416018.webp',
      },
    ],
    image:
      'https://cityfurnish.com/blog/wp-content/uploads/2024/02/alexa-6-seater-dining-table-with-4-chairs-and-bench-1-1694416018.webp',
    ratings: 1.5,
    reviews: [
      {
        user: 'Mahmud Huyton',
        comment: 'Fabric stains easily and the storage space is smaller than advertised.',
        rating: 2.8,
      },
      {
        user: 'Nonie Whiff',
        comment: 'Comfortable footrest and matches our decor perfectly.',
        rating: 3.4,
      },
      {
        user: 'Sean Tunney',
        comment: 'Excellent quality and the rose gold finish is stunning.',
        rating: 4.6,
      },
      {
        user: 'Mignonne Fairebrother',
        comment: 'Legs arrived wobbly and the fabric has loose threads.',
        rating: 1.5,
      },
      {
        user: 'Dorrie Olensby',
        comment: 'Perfect addition to our living room. Very sturdy and stylish.',
        rating: 4.8,
      },
    ],
    tags: ['living-room', 'storage', 'footrest', 'decor', 'multifunctional'],
    shippingInfo: { weight: 194.81, deliveryTime: '12-14 days' },
    warranty: null,
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '421711c0-f53f-452a-b332-72358069b7a3',
    name: 'Fire Pit Dining Set',
    arrivalDate: '2024-01-30',
    price: 620.54,
    discount: 6,
    stock: 18,
    description: 'Complete outdoor dining experience with built-in fire pit and comfortable seating.',
    dimensions: { height: '75cm', width: '150cm', depth: '150cm' },
    size: 'large',
    material: 'metal',
    category: 'Outdoor',
    status: ['top seller'],
    colors: [
      {
        name: 'Brown',
        hex: '#964B00',
        image: 'https://www.lifestylefurnitureplus.com/wp-content/uploads/2023/08/960x860-Nolan-Nixon-003.png',
      },
      { name: 'Black', hex: '#000000', image: '/images/image-placeholder.png' },
      { name: 'Rose Gold', hex: '#B76E79', image: '/images/image-placeholder.png' },
      { name: 'Burgundy', hex: '#800020', image: '/images/image-placeholder.png' },
      { name: 'Sky Blue', hex: '#87CEEB', image: '/images/image-placeholder.png' },
    ],
    image: 'https://www.lifestylefurnitureplus.com/wp-content/uploads/2023/08/960x860-Nolan-Nixon-003.png',
    ratings: 4.0,
    reviews: [
      {
        user: 'Helenka Handsheart',
        comment: 'Perfect for evening gatherings. The fire pit works great.',
        rating: 3.5,
      },
      {
        user: 'Klemens Beldon',
        comment: 'Assembly was challenging but the end result is beautiful.',
        rating: 2.0,
      },
    ],
    tags: ['outdoor', 'dining', 'fire-pit', 'patio', 'entertaining'],
    shippingInfo: { weight: 47.89, deliveryTime: '5-12 days' },
    warranty: null,
    returnPolicy: null,
    style: 'Traditional',
  },
  {
    _id: '585c4aaa-e0e2-4939-a8b4-c0915eb0e610',
    name: 'Deluxe Velvet Sofa',
    arrivalDate: '2024-04-15',
    price: 668.76,
    discount: 15,
    stock: null,
    description: 'Plush velvet sofa with deep seating and elegant tapered legs for a luxurious look.',
    dimensions: { height: '85cm', width: '210cm', depth: '95cm' },
    size: 'large',
    material: 'wood',
    category: 'Living Room',
    status: ['new arrival', 'top seller'],
    colors: [
      {
        name: 'Forest Green',
        hex: '#228B22',
        image:
          'https://homelinefurniture.ie/media/catalog/product/cache/4333fa618451a5190449de1dd5eb7f37/6/2/62725.jpeg',
      },
    ],
    image: 'https://homelinefurniture.ie/media/catalog/product/cache/4333fa618451a5190449de1dd5eb7f37/6/2/62725.jpeg',
    ratings: 4.2,
    reviews: [
      {
        user: 'Rufus Synan',
        comment: 'Color is beautiful but the cushions flatten quickly.',
        rating: 1.3,
      },
      {
        user: 'Eva Huckett',
        comment: 'Extremely comfortable and the velvet is high quality.',
        rating: 3.8,
      },
      {
        user: 'Morgun Beaulieu',
        comment: 'Perfect centerpiece for our living room. Worth every penny.',
        rating: 4.1,
      },
      {
        user: 'Norah Bynert',
        comment: 'Delivery was delayed but the sofa itself is gorgeous.',
        rating: 3.0,
      },
      {
        user: 'Myriam Bertin',
        comment: 'The forest green color is even more beautiful in person.',
        rating: 3.9,
      },
    ],
    tags: ['luxury', 'living-room', 'velvet', 'statement-piece', 'comfort'],
    shippingInfo: { weight: 89.36, deliveryTime: '2-12 days' },
    warranty: null,
    returnPolicy: null,
    style: 'Traditional',
  },
  {
    _id: '24589f8e-a68d-47a7-9fe1-99309528facc',
    name: 'Compact Computer Desk',
    arrivalDate: '2023-10-05',
    price: 848.24,
    discount: null,
    stock: 15,
    description: 'Ergonomic workspace solution with cable management and sturdy tempered glass top.',
    dimensions: { height: '75cm', width: '120cm', depth: '60cm' },
    size: 'medium',
    material: 'glass',
    category: 'Office Furniture',
    status: [],
    colors: [
      {
        name: 'Navy Blue',
        hex: '#000080',
        image:
          'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1678394427-screen-shot-2023-03-09-at-3-39-50-pm-640a441b4865a.png?crop=0.958xw:0.955xh;0.0144xw,0&resize=980:*',
      },
      { name: 'Blue', hex: '#0000FF', image: '/images/image-placeholder.png' },
      { name: 'Orange', hex: '#FFA500', image: '/images/image-placeholder.png' },
      { name: 'Black', hex: '#000000', image: '/images/image-placeholder.png' },
    ],
    image:
      'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1678394427-screen-shot-2023-03-09-at-3-39-50-pm-640a441b4865a.png?crop=0.958xw:0.955xh;0.0144xw,0&resize=980:*',
    ratings: 4.7,
    reviews: [
      {
        user: 'Birch Leverington',
        comment: 'Perfect size for small spaces. The glass surface is easy to clean.',
        rating: 4.7,
      },
    ],
    tags: ['office', 'workspace', 'ergonomic', 'modern', 'home-office'],
    shippingInfo: { weight: 149.44, deliveryTime: '7-8 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '6cbd6721-1c79-4208-91cf-65286fa4faaf',
    name: 'Luxe Velvet Sofa',
    arrivalDate: '2024-05-01',
    price: 899,
    discount: null,
    stock: 8,
    description:
      'Indulgent comfort wrapped in luxurious velvet. This plush 3-seater features deep cushioning and sleek lines for a refined look that transforms any living space into a relaxing haven.',
    dimensions: { height: '85cm', width: '210cm', depth: '90cm' },
    size: 'large',
    material: 'velvet & hardwood',
    category: 'Living Room',
    status: ['new arrival'],
    colors: [
      { name: 'Teal', hex: '#439792', image: '/images/luxe-velvet-teal.jpg' },
      { name: 'Rust Orange', hex: '#bf4b1c', image: '/images/luxe-velvet-orange.jpg' },
      { name: 'Caramel Brown', hex: '#c18f5b', image: '/images/luxe-velvet-brown.jpg' },
      { name: 'Light Blue', hex: '#abc3e9', image: '/images/luxe-velvet-light-blue.jpg' },
      { name: 'Sand', hex: '#c9bc90', image: '/images/luxe-velvet-sand.jpg' },
      { name: 'Gold', hex: '#dd9046', image: '/images/luxe-velvet-gold.jpg' },
    ],
    image: '/images/luxe-velvet-teal.jpg',
    ratings: 4.3,
    reviews: [
      {
        user: 'Claire Bennett',
        comment: 'Absolutely in love with the color and softness. Adds a luxe feel to my space.',
        rating: 4.9,
      },
      {
        user: 'Daniel Okafor',
        comment: 'The cushions are deep and plush. Ideal for lounging with family.',
        rating: 4.5,
      },
      {
        user: 'Amira El-Sayed',
        comment: "Fabric is smooth and doesn't trap pet hair. A great plus for pet owners.",
        rating: 4.2,
      },
      {
        user: 'Tobias Schmidt',
        comment: 'Setup took less than 15 minutes. Very impressed with the quality of materials.',
        rating: 4.4,
      },
      {
        user: 'Yumi Aoki',
        comment: 'Would love slightly firmer back support, but overall a gorgeous piece.',
        rating: 3.9,
      },
      {
        user: 'Marco De Luca',
        comment: 'Looks even better in person. The velvet has a rich texture under light.',
        rating: 4.8,
      },
      {
        user: 'Lina Novak',
        comment: 'My guests keep asking where I got it. Stylish and surprisingly affordable.',
        rating: 4.6,
      },
      {
        user: 'Aarav Mehta',
        comment: 'Comfortable to sit on for long hours. Great for movie nights.',
        rating: 4.1,
      },
      {
        user: 'Juliette Dubois',
        comment: 'Color matches the product photos perfectly. Delivery was quick too.',
        rating: 4.7,
      },
      {
        user: 'Oscar Thompson',
        comment: 'Minor wobble on one leg but easy to fix. Otherwise, very satisfied.',
        rating: 3.8,
      },
    ],
    tags: ['living-room', 'luxury', 'velvet', 'comfortable', 'sofa'],
    shippingInfo: { weight: 92.3, deliveryTime: '5-6 days' },
    warranty: '2 years',
    returnPolicy: '45-day return',
    style: 'Traditional',
  },
  {
    _id: '3a8b9c7d-6e5f-4a3b-9c8d-7e6f5a4b3c2d',
    name: 'Modern Platform Bed',
    arrivalDate: '2024-04-20',
    price: 799.99,
    discount: 15,
    stock: 12,
    description:
      'Sleek low-profile platform bed with built-in storage drawers and upholstered headboard. Designed for contemporary bedrooms with clean lines.',
    dimensions: { height: '60cm', width: '180cm', depth: '200cm' },
    size: 'large',
    material: 'fabric upholstery with wooden frame',
    category: 'Bedroom',
    status: ['new arrival'],
    colors: [
      { name: 'Charcoal', hex: '#36454F', image: 'https://i.ebayimg.com/images/g/W18AAOSw-dllvwb3/s-l1200.jpg' },
      {
        name: 'Ivory',
        hex: '#FFFFF0',
        image:
          'https://i5.walmartimages.com/seo/Elegant-Stylish-Gray-Faux-Leather-Upholstered-King-Size-Platform-Bed-Frame-LED-Lighting-Sturdy-Wood-Slat-Support-Easy-Assemble-No-Box-Spring-Needed-F_a879c924-c693-44b7-a103-54c375758782.1b7f439389c32064bddf9ccf0a3251cd.jpeg',
      },
      {
        name: 'Navy',
        hex: '#000080',
        image: 'https://i.pinimg.com/736x/ea/0c/a5/ea0ca54bb69f4238f2a014c1db1f841b.jpg',
      },
    ],
    image: 'https://i.ebayimg.com/images/g/W18AAOSw-dllvwb3/s-l1200.jpg',
    ratings: 4.6,
    reviews: [
      {
        user: 'Emma Rodriguez',
        comment: 'Incredibly sturdy and the storage drawers are a game-changer!',
        rating: 5,
      },
      {
        user: 'Lucas Chen',
        comment: 'Assembly took 2 hours but the instructions were clear. Very comfortable.',
        rating: 4,
      },
    ],
    tags: ['bedroom', 'storage', 'platform', 'modern'],
    shippingInfo: { weight: 95.5, deliveryTime: '7-10 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '4b3c2d1e-9f8a-7b6c-5d4e-3f2a1b0c9d8e',
    name: 'Executive Office Chair',
    arrivalDate: '2024-03-10',
    price: 499.95,
    discount: null,
    stock: 7,
    description:
      'Ergonomic high-back leather chair with adjustable lumbar support, tilt mechanism, and breathable mesh back.',
    dimensions: { height: '120cm', width: '70cm', depth: '65cm' },
    size: 'medium',
    material: 'genuine leather',
    category: 'Office Furniture',
    status: ['top seller'],
    colors: [
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://melcom.com/media/catalog/product/cache/d0e1b0d5c74d14bfa9f7dd43ec52d082/1/4/149359a.jpg',
      },
      {
        name: 'Chestnut',
        hex: '#954535',
        image:
          'https://media-cldnry.s-nbcnews.com/image/upload/newscms/2024_34/3660043/lifeform2390ultimateexecutive-tribecamerlot-3a220830-669e-42c9-b326-7de1eb377637-700x700-66c79ab57986d.jpg',
      },
    ],
    image: 'https://melcom.com/media/catalog/product/cache/d0e1b0d5c74d14bfa9f7dd43ec52d082/1/4/149359a.jpg',
    ratings: 4.8,
    reviews: [
      {
        user: 'David Kim',
        comment: 'Worth every penny for back support during long work hours.',
        rating: 5,
      },
      {
        user: 'Sophia Martinez',
        comment: 'The leather smells amazing and the adjustments are perfect.',
        rating: 5,
      },
    ],
    tags: ['office', 'ergonomic', 'chair', 'executive'],
    shippingInfo: { weight: 32.8, deliveryTime: '5-7 days' },
    warranty: '5 years',
    returnPolicy: '60-day return',
    style: 'Modern',
  },
  {
    _id: '5c4d3e2f-1a0b-9c8d-7e6f-5a4b3c2d1e0f',
    name: 'Rustic Dining Table',
    arrivalDate: '2024-05-05',
    price: 1299.0,
    discount: 20,
    stock: 5,
    description: 'Handcrafted solid oak table with live edge details and industrial metal legs. Seats 8 comfortably.',
    dimensions: { height: '75cm', width: '240cm', depth: '100cm' },
    size: 'large',
    material: 'reclaimed oak',
    category: 'Dining',
    status: ['new arrival', 'top seller'],
    colors: [
      {
        name: 'Natural Oak',
        hex: '#D2B48C',
        image:
          'https://woodlandcreekfurniture.com/media/catalog/product/cache/1044726d93dd0fc5b52ac7ed430bb624/t/i/timber-haven-rustic-barnwood-dining-table-11.jpg',
      },
      {
        name: 'Walnut Stain',
        hex: '#5C4033',
        image:
          'https://logfurnitureplace.com/media/catalog/product/cache/1044726d93dd0fc5b52ac7ed430bb624/r/u/rustic-farmstead-gathering-dining-table-dt00402-13.jpg',
      },
    ],
    image:
      'https://woodlandcreekfurniture.com/media/catalog/product/cache/1044726d93dd0fc5b52ac7ed430bb624/t/i/timber-haven-rustic-barnwood-dining-table-11.jpg',
    ratings: 4.9,
    reviews: [
      {
        user: 'Olivia Thompson',
        comment: 'Stunning craftsmanship. The live edge is a conversation starter!',
        rating: 5,
      },
    ],
    tags: ['dining', 'rustic', 'handcrafted', 'farmhouse'],
    shippingInfo: { weight: 150.2, deliveryTime: '14-21 days' },
    warranty: 'Lifetime',
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '6d5e4f3a-2b1c-0d9e-8f7a-6b5c4d3e2f1a',
    name: 'Outdoor Lounge Set',
    arrivalDate: '2024-04-01',
    price: 1599.5,
    discount: 25,
    stock: 3,
    description:
      'Weather-resistant wicker patio set with thick cushions and tempered glass coffee table. Includes 2 armchairs and 1 loveseat.',
    dimensions: { height: '85cm', width: '300cm', depth: '180cm' },
    size: 'large',
    material: 'synthetic wicker',
    category: 'Outdoor',
    status: ['top seller'],
    colors: [
      {
        name: 'Taupe',
        hex: '#483C32',
        image: 'https://www.wickerfurnituredirect.com.au/assets/full/WFD-Majeston-black.jpg?20231029150707',
      },
      {
        name: 'Slate',
        hex: '#708090',
        image: 'https://www.wickerfurnituredirect.com.au/assets/images/cushion/white-majeston-grey.jpg',
      },
    ],
    image: 'https://www.wickerfurnituredirect.com.au/assets/full/WFD-Majeston-black.jpg?20231029150707',
    ratings: 4.7,
    reviews: [
      {
        user: 'Michael Johnson',
        comment: 'Survived a whole winter outside with no damage. Cushions stay dry!',
        rating: 5,
      },
      {
        user: 'Aisha Williams',
        comment: "Super comfortable and the color hasn't faded after 6 months in sun.",
        rating: 4,
      },
    ],
    tags: ['patio', 'weatherproof', 'lounge', 'outdoor'],
    shippingInfo: { weight: 210.0, deliveryTime: '10-15 days' },
    warranty: '3 years',
    returnPolicy: '90-day return',
    style: 'Bohemian',
  },
  {
    _id: '7e6f5a4b-3c2d-1e0f-9a8b-7c6d5e4f3a2b',
    name: 'Minimalist Nightstand',
    arrivalDate: '2023-12-05',
    price: 249.99,
    discount: null,
    stock: 18,
    description:
      'Sleek floating nightstand with hidden storage compartment and wireless charging pad built into the top surface.',
    dimensions: { height: '50cm', width: '40cm', depth: '35cm' },
    size: 'small',
    material: 'MDF with matte laminate',
    category: 'Bedroom',
    status: [],
    colors: [
      {
        name: 'White',
        hex: '#FFFFFF',
        image: 'https://m.media-amazon.com/images/I/61aGChtf3oL._AC_UF894,1000_QL80_.jpg',
      },
      { name: 'Black', hex: '#000000', image: 'https://m.media-amazon.com/images/I/61w31Rxsn7L.jpg' },
    ],
    image: 'https://m.media-amazon.com/images/I/61aGChtf3oL._AC_UF894,1000_QL80_.jpg',
    ratings: 4.4,
    reviews: [
      {
        user: 'Ethan Brown',
        comment: 'The wireless charging is brilliant! Fits my phone perfectly.',
        rating: 5,
      },
      {
        user: 'Isabella Lee',
        comment: 'Modern look but the storage is smaller than expected.',
        rating: 3,
      },
    ],
    tags: ['bedroom', 'nightstand', 'charging', 'modern'],
    shippingInfo: { weight: 15.3, deliveryTime: '3-5 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Scandinavian',
  },
  {
    _id: '8f7a6b5c-4d3e-2f1a-0b9c-8d7e6f5a4b3c',
    name: 'Industrial Bookshelf',
    arrivalDate: '2024-05-12',
    price: 649.0,
    discount: 10,
    stock: 9,
    description:
      'Steel-framed open shelving unit with reclaimed wood shelves. Adjustable shelf heights with visible rivet details.',
    dimensions: { height: '180cm', width: '120cm', depth: '40cm' },
    size: 'large',
    material: 'steel and reclaimed pine',
    category: 'Living Room',
    status: ['new arrival'],
    colors: [
      {
        name: 'Blackened Steel',
        hex: '#1A1A1A',
        image:
          'https://i5.walmartimages.com/asr/cde443fa-3c7c-4056-94ce-35c43312ece6.2f1385fe40cb3b21793dd13695006f7c.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
      },
      {
        name: 'Raw Steel',
        hex: '#71797E',
        image: 'https://m.media-amazon.com/images/I/81flDumgBGS._AC_UF894,1000_QL80_.jpg',
      },
    ],
    image:
      'https://i5.walmartimages.com/asr/cde443fa-3c7c-4056-94ce-35c43312ece6.2f1385fe40cb3b21793dd13695006f7c.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
    ratings: 4.5,
    reviews: [
      {
        user: 'Noah Garcia',
        comment: 'Perfect industrial aesthetic. Holds all my books securely.',
        rating: 5,
      },
      {
        user: 'Sophie Wilson',
        comment: 'Heavier than expected but incredibly sturdy.',
        rating: 4,
      },
    ],
    tags: ['bookshelf', 'industrial', 'adjustable', 'living-room'],
    shippingInfo: { weight: 85.7, deliveryTime: '7-12 days' },
    warranty: '5 years',
    returnPolicy: '30-day return',
    style: 'Industrial',
  },
  {
    _id: '9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d',
    name: 'Convertible Sofa Bed',
    arrivalDate: '2024-02-15',
    price: 1199.0,
    discount: 30,
    stock: 6,
    description:
      'Space-saving 3-seater that converts to queen bed in seconds. Features high-density foam and pocket coil hybrid mattress.',
    dimensions: { height: '90cm', width: '210cm', depth: '95cm' },
    size: 'large',
    material: 'performance fabric',
    category: 'Living Room',
    status: ['top seller'],
    colors: [
      {
        name: 'Graphite',
        hex: '#383838',
        image:
          'https://i5.walmartimages.com/seo/3-1-Convertible-Sleeper-Sofa-Bed-53-Modern-Convertible-Sofa-Bed-2-Detachable-Arm-Pockets-Velvet-Pull-Couch-Pull-Bed-Living-Room-Furniture-Black_0bf1700c-c974-4fe0-aab0-8b449b8636bf.716caeaf94e2651779019ec3b807edb0.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
      },
      { name: 'Oatmeal', hex: '#EDE6D6', image: 'https://i.ebayimg.com/images/g/JwsAAOSw1Dpkv6HH/s-l1200.jpg' },
    ],
    image:
      'https://i5.walmartimages.com/seo/3-1-Convertible-Sleeper-Sofa-Bed-53-Modern-Convertible-Sofa-Bed-2-Detachable-Arm-Pockets-Velvet-Pull-Couch-Pull-Bed-Living-Room-Furniture-Black_0bf1700c-c974-4fe0-aab0-8b449b8636bf.716caeaf94e2651779019ec3b807edb0.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
    ratings: 4.3,
    reviews: [
      {
        user: 'Liam Anderson',
        comment: 'Game-changer for my studio apartment. Comfortable as both sofa and bed.',
        rating: 5,
      },
      {
        user: 'Ava Martinez',
        comment: 'Conversion mechanism is smooth but the mattress could be thicker.',
        rating: 4,
      },
    ],
    tags: ['sofa', 'convertible', 'space-saving', 'apartment'],
    shippingInfo: { weight: 110.5, deliveryTime: '10-14 days' },
    warranty: '3 years',
    returnPolicy: '60-day return',
    style: 'Modern',
  },
  {
    _id: '0b9c8d7e-6f5a-4b3c-2d1e-0f9a8b7c6d5e',
    name: 'Glass Display Cabinet',
    arrivalDate: '2023-11-20',
    price: 899.95,
    discount: null,
    stock: 4,
    description:
      'Museum-quality display case with tempered glass panels, LED lighting, and lockable doors. Perfect for collectibles.',
    dimensions: { height: '200cm', width: '100cm', depth: '45cm' },
    size: 'large',
    material: 'glass and steel',
    category: 'Living Room',
    status: [],
    colors: [
      {
        name: 'Chrome',
        hex: '#E8E8E8',
        image: 'https://theshopfittingshop.co.uk/wp-content/uploads/2023/01/Cabinet.webp',
      },
      {
        name: 'Black',
        hex: '#000000',
        image: '/https://theshopfittingshop.co.uk/wp-content/uploads/2019/04/R1585.jpg',
      },
    ],
    image: 'https://theshopfittingshop.co.uk/wp-content/uploads/2023/01/Cabinet.webp',
    ratings: 4.9,
    reviews: [
      {
        user: 'Mia Thompson',
        comment: 'The LED lighting makes my collectibles look incredible!',
        rating: 5,
      },
      {
        user: 'James Wilson',
        comment: 'Assembly was complex but the instructions were thorough.',
        rating: 4,
      },
    ],
    tags: ['display', 'cabinet', 'lighting', 'collectibles'],
    shippingInfo: { weight: 95.0, deliveryTime: '14-21 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '1c0d9e8f-7a6b-5c4d-3e2f-1a0b9c8d7e6f',
    name: 'Adjustable Standing Desk',
    arrivalDate: '2024-05-08',
    price: 749.0,
    discount: 15,
    stock: 11,
    description:
      'Electric height-adjustable desk with programmable memory settings, built-in USB ports, and eco-friendly bamboo top.',
    dimensions: { height: '72-122cm', width: '150cm', depth: '75cm' },
    size: 'medium',
    material: 'bamboo and steel',
    category: 'Office Furniture',
    status: ['new arrival'],
    colors: [
      {
        name: 'Natural Bamboo',
        hex: '#E3C9A0',
        image:
          'https://www.vari.com/dw/image/v2/BDFT_PRD/on/demandware.static/-/Sites-vari-master-catalog/default/dwaf64947c/images/large/FD-ESD6030/400803-reclaimed-wood/vari-electric-standing_400803_reclaimedwood_wfh_s.jpg?sw=800&sh=800',
      },
      { name: 'Carbon Black', hex: '#333333', image: 'https://theomnidesk.com/cdn/shop/files/Black5.png?v=1739340470' },
    ],
    image:
      'https://www.vari.com/dw/image/v2/BDFT_PRD/on/demandware.static/-/Sites-vari-master-catalog/default/dwaf64947c/images/large/FD-ESD6030/400803-reclaimed-wood/vari-electric-standing_400803_reclaimedwood_wfh_s.jpg?sw=800&sh=800',
    ratings: 4.7,
    reviews: [
      {
        user: 'Benjamin Lee',
        comment: 'Life-changing for my back pain. The silent motor is amazing.',
        rating: 5,
      },
      {
        user: 'Charlotte Kim',
        comment: 'The bamboo surface is beautiful and easy to clean.',
        rating: 5,
      },
    ],
    tags: ['desk', 'adjustable', 'ergonomic', 'standing'],
    shippingInfo: { weight: 68.9, deliveryTime: '7-10 days' },
    warranty: '10 years',
    returnPolicy: '60-day return',
    style: 'Modern',
  },
  {
    _id: '1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p',
    name: 'Mid-Century Armchair',
    arrivalDate: '2024-03-05',
    price: 349.99,
    discount: 10,
    stock: 15,
    description: 'Classic mid-century design with walnut legs and premium upholstery for timeless elegance.',
    dimensions: { height: '80cm', width: '65cm', depth: '70cm' },
    size: 'medium',
    material: 'fabric & walnut',
    category: 'Living Room',
    status: ['top seller'],
    colors: [
      {
        name: 'Mustard',
        hex: '#FFDB58',
        image:
          'https://theoldcinema.b-cdn.net/media/catalog/product/cache/9e466686975e05e3305ab6e5d5888b6a/1/9/1960_henryk_lis_mid_century_armchair_in_goldenrod_velvet_33_46067_copy.jpg',
      },
      {
        name: 'Olive Green',
        hex: '#6B8E23',
        image: 'https://thedesignark.com.au/cdn/shop/products/MidCenturyArmchairNewUpholstery4.jpg?v=1622960899',
      },
    ],
    image:
      'https://theoldcinema.b-cdn.net/media/catalog/product/cache/9e466686975e05e3305ab6e5d5888b6a/1/9/1960_henryk_lis_mid_century_armchair_in_goldenrod_velvet_33_46067_copy.jpg',
    ratings: 4.5,
    reviews: [
      {
        user: 'Emma Wilson',
        comment: 'Beautiful craftsmanship and incredibly comfortable.',
        rating: 5,
      },
    ],
    tags: ['armchair', 'mid-century', 'living-room', 'designer'],
    shippingInfo: { weight: 25.5, deliveryTime: '5-7 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '2b3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q',
    name: 'Wall-Mounted Floating Desk',
    arrivalDate: '2024-05-14',
    price: 199.99,
    discount: null,
    stock: 20,
    description: 'Space-saving wall-mounted desk with cable management for modern home offices.',
    dimensions: { height: '75cm', width: '120cm', depth: '45cm' },
    size: 'medium',
    material: 'engineered wood',
    category: 'Office Furniture',
    status: ['new arrival'],
    colors: [
      {
        name: 'White Oak',
        hex: '#E8D3B9',
        image:
          'https://i5.walmartimages.com/seo/Zimtown-Wall-Mounted-Computer-Desk-Floating-Office-Home-PC-Table-with-Storage-Shelf-White_e432661d-9211-4614-b39f-59542265d54e_1.3d0d93f5ca6f5de1b4f4620bfdcb7189.jpeg',
      },
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://images-cdn.ubuy.co.in/666215ec4ff15a6a887f3439-prepac-floating-desk-versatile-wall.jpg',
      },
    ],
    image:
      'https://i5.walmartimages.com/seo/Zimtown-Wall-Mounted-Computer-Desk-Floating-Office-Home-PC-Table-with-Storage-Shelf-White_e432661d-9211-4614-b39f-59542265d54e_1.3d0d93f5ca6f5de1b4f4620bfdcb7189.jpeg',
    ratings: 4.2,
    reviews: [
      {
        user: 'David Chen',
        comment: 'Perfect for my small apartment. Installation was straightforward.',
        rating: 4,
      },
    ],
    tags: ['desk', 'wall-mounted', 'space-saving', 'home-office'],
    shippingInfo: { weight: 18.7, deliveryTime: '3-5 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '3c4d5e6f-7g8h-9i0j-1k2l-3m4n5o6p7q8r',
    name: 'Modular Sectional Sofa',
    arrivalDate: '2024-04-25',
    price: 1899.99,
    discount: 15,
    stock: 8,
    description: 'Customizable sectional sofa with reversible chaise and premium foam cushions.',
    dimensions: { height: '85cm', width: '300cm', depth: '160cm' },
    size: 'large',
    material: 'performance fabric',
    category: 'Living Room',
    status: ['top seller'],
    colors: [
      {
        name: 'Charcoal',
        hex: '#36454F',
        image:
          'https://ak1.ostkcdn.com/images/products/is/images/direct/8a937f1c2db2caf056d50204e674132aa4c03d0d/Cloud-Modular-Sectional-Sofa-with-2-Storage-Ottomans%2C160.6%22-Down-Filled-Comfort-U-Shaped-Sofa-Couch-for-Living-Room.jpg?impolicy=medium',
      },
      {
        name: 'Navy',
        hex: '#000080',
        image:
          'https://luxuryhomefurniture.net/cdn/shop/files/Meridian_2023-06-08T00_01_19.532007_tzyibasiqg.jpg?v=1744809765&width=5760',
      },
    ],
    image:
      'https://ak1.ostkcdn.com/images/products/is/images/direct/8a937f1c2db2caf056d50204e674132aa4c03d0d/Cloud-Modular-Sectional-Sofa-with-2-Storage-Ottomans%2C160.6%22-Down-Filled-Comfort-U-Shaped-Sofa-Couch-for-Living-Room.jpg?impolicy=medium',
    ratings: 4.7,
    reviews: [
      {
        user: 'Sarah Johnson',
        comment: 'Incredibly comfortable and the modular design is perfect for our space.',
        rating: 5,
      },
    ],
    tags: ['sectional', 'sofa', 'living-room', 'modular'],
    shippingInfo: { weight: 150.2, deliveryTime: '10-14 days' },
    warranty: '3 years',
    returnPolicy: '60-day return',
    style: 'Modern',
  },
  {
    _id: '4d5e6f7g-8h9i-0j1k-2l3m-4n5o6p7q8r9s',
    name: 'Industrial Bar Stool',
    arrivalDate: '2023-12-12',
    price: 149.99,
    discount: null,
    stock: 25,
    description: 'Adjustable height bar stool with steel frame and distressed leather seat.',
    dimensions: { height: '65-85cm', width: '45cm', depth: '45cm' },
    size: 'small',
    material: 'steel & leather',
    category: 'Dining',
    status: [],
    colors: [
      {
        name: 'Brown Leather',
        hex: '#5C4033',
        image: 'https://m.media-amazon.com/images/I/71zzo0WWs0S._AC_SL1500_.jpg',
      },
      {
        name: 'Black Leather',
        hex: '#000000',
        image: 'https://m.media-amazon.com/images/I/818idIqPqnL._AC_UF894,1000_QL80_.jpg',
      },
    ],
    image: 'https://m.media-amazon.com/images/I/71zzo0WWs0S._AC_SL1500_.jpg',
    ratings: 4.3,
    reviews: [
      {
        user: 'Michael Brown',
        comment: 'Sturdy construction and comfortable for long sitting.',
        rating: 4,
      },
    ],
    tags: ['bar stool', 'industrial', 'kitchen', 'adjustable'],
    shippingInfo: { weight: 12.8, deliveryTime: '4-6 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Industrial',
  },
  {
    _id: '5e6f7g8h-9i0j-1k2l-3m4n-5o6p7q8r9s0t',
    name: 'Acacia Wood Coffee Table',
    arrivalDate: '2024-02-20',
    price: 399.99,
    discount: 20,
    stock: 12,
    description: 'Solid acacia wood coffee table with natural grain patterns and metal hairpin legs.',
    dimensions: { height: '45cm', width: '120cm', depth: '60cm' },
    size: 'medium',
    material: 'acacia wood',
    category: 'Living Room',
    status: ['new arrival'],
    colors: [
      {
        name: 'Natural',
        hex: '#D2B48C',
        image:
          'https://inmarwar.com/cdn/shop/files/coffee-table-1_f9a3f749-8d28-492b-b175-e9c44a68b2f5.jpg?v=1712817211&width=1080',
      },
      {
        name: 'Dark Stain',
        hex: '#5C4033',
        image:
          'https://assets.mydeal.com.au/47286/cleo-coffee-table-oak-medium-9324472_01.jpg?v=1728556812&imgclass=dealpageimage',
      },
    ],
    image:
      'https://inmarwar.com/cdn/shop/files/coffee-table-1_f9a3f749-8d28-492b-b175-e9c44a68b2f5.jpg?v=1712817211&width=1080',
    ratings: 4.6,
    reviews: [
      {
        user: 'Jennifer Lee',
        comment: 'Beautiful wood grain and very sturdy construction.',
        rating: 5,
      },
    ],
    tags: ['coffee table', 'living-room', 'wood', 'mid-century'],
    shippingInfo: { weight: 32.5, deliveryTime: '7-10 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Scandinavian',
  },
  {
    _id: '6f7g8h9i-0j1k-2l3m-4n5o-6p7q8r9s0t1u',
    name: 'Overbed Storage Table',
    arrivalDate: '2024-01-08',
    price: 129.99,
    discount: null,
    stock: 18,
    description: 'Hospital-style overbed table with adjustable height and locking wheels for mobility.',
    dimensions: { height: '70-100cm', width: '60cm', depth: '40cm' },
    size: 'medium',
    material: 'metal & MDF',
    category: 'Bedroom',
    status: [],
    colors: [
      { name: 'White', hex: '#FFFFFF', image: 'https://i.ebayimg.com/images/g/ZTgAAOSwfg1k6c12/s-l400.jpg' },
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://m.media-amazon.com/images/I/81ZjrWwjQnL._AC_UF894,1000_QL80_.jpg',
      },
    ],
    image: 'https://i.ebayimg.com/images/g/ZTgAAOSwfg1k6c12/s-l400.jpg',
    ratings: 4.1,
    reviews: [
      {
        user: 'Robert Taylor',
        comment: 'Perfect for working from bed or eating meals comfortably.',
        rating: 4,
      },
    ],
    tags: ['bedroom', 'adjustable', 'mobile', 'hospital-table'],
    shippingInfo: { weight: 15.2, deliveryTime: '5-7 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Industrial',
  },
  {
    _id: '7g8h9i0j-1k2l-3m4n-5o6p-7q8r9s0t1u2v',
    name: 'Leather Recliner Chair',
    arrivalDate: '2024-03-18',
    price: 799.99,
    discount: 25,
    stock: 10,
    description: 'Premium leather recliner with power adjustment and built-in USB charging port.',
    dimensions: { height: '110cm', width: '90cm', depth: '95cm' },
    size: 'large',
    material: 'genuine leather',
    category: 'Living Room',
    status: ['top seller'],
    colors: [
      {
        name: 'Cognac',
        hex: '#9A463D',
        image: 'https://images-cdn.ubuy.com.sa/6537bee5d5863235dd03e1be-kasunpul-large-power-lift-recliner-chair.jpg',
      },
      { name: 'Black', hex: '#000000', image: 'https://m.media-amazon.com/images/I/71azdRIE2nL.jpg' },
    ],
    image: 'https://images-cdn.ubuy.com.sa/6537bee5d5863235dd03e1be-kasunpul-large-power-lift-recliner-chair.jpg',
    ratings: 4.8,
    reviews: [
      {
        user: 'Thomas Wilson',
        comment: "The most comfortable chair I've ever owned. Worth every penny.",
        rating: 5,
      },
    ],
    tags: ['recliner', 'leather', 'living-room', 'power'],
    shippingInfo: { weight: 65.3, deliveryTime: '10-14 days' },
    warranty: '5 years',
    returnPolicy: '60-day return',
    style: 'Traditional',
  },
  {
    _id: '8h9i0j1k-2l3m-4n5o-6p7q-8r9s0t1u2v3w',
    name: 'Rustic Console Table',
    arrivalDate: '2023-11-25',
    price: 279.99,
    discount: null,
    stock: 14,
    description: 'Handcrafted console table with live edge top and black iron legs for farmhouse charm.',
    dimensions: { height: '80cm', width: '120cm', depth: '35cm' },
    size: 'medium',
    material: 'reclaimed wood',
    category: 'Living Room',
    status: [],
    colors: [
      {
        name: 'Natural',
        hex: '#D2B48C',
        image:
          'https://woodlandcreekfurniture.com/media/catalog/product/cache/1044726d93dd0fc5b52ac7ed430bb624/c/u/customsofatable_1.jpg',
      },
      {
        name: 'Weathered Gray',
        hex: '#808080',
        image:
          'https://i0.wp.com/inbetweenchaos.com/wp-content/uploads/2016/04/Ana-White-Rustic-X-Console-Table-300x275.jpeg?resize=300%2C275',
      },
    ],
    image:
      'https://woodlandcreekfurniture.com/media/catalog/product/cache/1044726d93dd0fc5b52ac7ed430bb624/c/u/customsofatable_1.jpg',
    ratings: 4.4,
    reviews: [
      {
        user: 'Lisa Martinez',
        comment: 'Beautiful craftsmanship and perfect for our entryway.',
        rating: 5,
      },
    ],
    tags: ['console', 'entryway', 'farmhouse', 'rustic'],
    shippingInfo: { weight: 28.7, deliveryTime: '7-10 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '9i0j1k2l-3m4n-5o6p-7q8r-9s0t1u2v3w4x',
    name: 'Glass TV Stand',
    arrivalDate: '2024-05-03',
    price: 349.99,
    discount: 10,
    stock: 9,
    description: 'Modern TV stand with tempered glass shelves and LED lighting for contemporary living rooms.',
    dimensions: { height: '50cm', width: '180cm', depth: '40cm' },
    size: 'large',
    material: 'glass & metal',
    category: 'Living Room',
    status: ['new arrival'],
    colors: [
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://m.media-amazon.com/images/I/81rfqs5Ty6L._AC_UF350,350_QL80_.jpg',
      },
      {
        name: 'Chrome',
        hex: '#E8E8E8',
        image:
          'https://assets.wfcdn.com/im/56910250/resize-h400-w400%5Ecompr-r85/2646/264685257/Jaevyn+TV+Stand+for+TVs+up+to+70%22.jpg',
      },
    ],
    image: 'https://m.media-amazon.com/images/I/81rfqs5Ty6L._AC_UF350,350_QL80_.jpg',
    ratings: 4.3,
    reviews: [
      {
        user: 'Daniel Kim',
        comment: 'Sleek design and the LED lighting is a nice touch.',
        rating: 4,
      },
    ],
    tags: ['tv stand', 'modern', 'living-room', 'led'],
    shippingInfo: { weight: 42.3, deliveryTime: '7-10 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '0j1k2l3m-4n5o-6p7q-8r9s-0t1u2v3w4x5y',
    name: 'Bamboo Shoe Rack',
    arrivalDate: '2024-02-10',
    price: 89.99,
    discount: null,
    stock: 22,
    description: 'Eco-friendly bamboo shoe organizer with 4 tiers and breathable design.',
    dimensions: { height: '80cm', width: '60cm', depth: '25cm' },
    size: 'medium',
    material: 'bamboo',
    category: 'Bedroom',
    status: [],
    colors: [
      {
        name: 'Natural',
        hex: '#E3C9A0',
        image: 'https://www.islandliving.sg/cdn/shop/products/BambooShoerack1.jpg?v=1662703726',
      },
    ],
    image: 'https://www.islandliving.sg/cdn/shop/products/BambooShoerack1.jpg?v=1662703726',
    ratings: 4.0,
    reviews: [
      {
        user: 'Amanda Chen',
        comment: 'Perfect size for our entryway and holds all our shoes neatly.',
        rating: 4,
      },
    ],
    tags: ['shoe rack', 'storage', 'entryway', 'bamboo'],
    shippingInfo: { weight: 8.5, deliveryTime: '3-5 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Scandinavian',
  },
  {
    _id: '1k2l3m4n-5o6p-7q8r-9s0t-1u2v3w4x5y6z',
    name: 'Hanging Egg Chair',
    arrivalDate: '2024-04-08',
    price: 499.99,
    discount: 15,
    stock: 7,
    description: 'Rattan hanging chair with comfortable cushion for indoor or covered outdoor use.',
    dimensions: { height: '150cm', width: '90cm', depth: '90cm' },
    size: 'large',
    material: 'rattan & fabric',
    category: 'Outdoor',
    status: ['top seller'],
    colors: [
      {
        name: 'Natural',
        hex: '#D2B48C',
        image:
          'https://therattancompany.co.uk/cdn/shop/collections/Zulu-Hanging-Egg-Chair-The-Rattan-Company.jpg?v=1565720028',
      },
      {
        name: 'White',
        hex: '#FFFFFF',
        image:
          'https://images.thdstatic.com/productImages/e095a780-725b-4f9d-803e-2c342240a9e0/svn/leisuremod-porch-swings-escw-40lgr-c3_600.jpg',
      },
    ],
    image:
      'https://therattancompany.co.uk/cdn/shop/collections/Zulu-Hanging-Egg-Chair-The-Rattan-Company.jpg?v=1565720028',
    ratings: 4.6,
    reviews: [
      {
        user: 'Sophia Rodriguez',
        comment: 'My favorite spot in the house! So comfortable and stylish.',
        rating: 5,
      },
    ],
    tags: ['hanging chair', 'rattan', 'outdoor', 'boho'],
    shippingInfo: { weight: 28.9, deliveryTime: '10-14 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Bohemian',
  },
  {
    _id: '2l3m4n5o-6p7q-8r9s-0t1u-2v3w4x5y6z7a',
    name: "Children's Study Desk",
    arrivalDate: '2024-03-30',
    price: 179.99,
    discount: null,
    stock: 16,
    description: 'Adjustable height desk with built-in storage and chair set for growing kids.',
    dimensions: { height: '60-75cm', width: '90cm', depth: '50cm' },
    size: 'small',
    material: 'MDF & plastic',
    category: 'Bedroom',
    status: ['new arrival'],
    colors: [
      {
        name: 'Pink',
        hex: '#FFC0CB',
        image:
          'https://www.ozstudydesks.com.au/cdn/shop/products/3_5d3097a2-cbff-4289-81d3-3762e0fcbdf5.jpg?v=1746838409',
      },
      {
        name: 'Blue',
        hex: '#0000FF',
        image:
          'https://www.ozstudydesks.com.au/cdn/shop/products/3_8fd0ae85-64c4-4876-9e7e-37049f1e18be.jpg?v=1746838412',
      },
    ],
    image: 'https://www.ozstudydesks.com.au/cdn/shop/products/3_5d3097a2-cbff-4289-81d3-3762e0fcbdf5.jpg?v=1746838409',
    ratings: 4.2,
    reviews: [
      {
        user: 'Emily Wilson',
        comment: 'Perfect size for my daughter and the adjustable height is great.',
        rating: 4,
      },
    ],
    tags: ['kids', 'desk', 'study', 'adjustable'],
    shippingInfo: { weight: 22.4, deliveryTime: '5-7 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '3m4n5o6p-7q8r-9s0t-1u2v-3w4x5y6z7a8b',
    name: 'Linen Upholstered Bed',
    arrivalDate: '2024-01-22',
    price: 1299.99,
    discount: 20,
    stock: 5,
    description: 'Luxury linen upholstered bed with tufted headboard and sturdy wooden frame.',
    dimensions: { height: '120cm', width: '180cm', depth: '210cm' },
    size: 'large',
    material: 'linen & wood',
    category: 'Bedroom',
    status: ['top seller'],
    colors: [
      {
        name: 'Taupe',
        hex: '#483C32',
        image: 'https://mybedtime.com.au/wp-content/uploads/product-images_1280x720_cleo.jpg',
      },
      {
        name: 'Dusty Blue',
        hex: '#6699CC',
        image:
          'https://cdn11.bigcommerce.com/s-c7l9ds/images/stencil/1280x1280/products/1399/6399/Alana-Bed__11056.1662440543.jpg?c=2',
      },
    ],
    image: 'https://mybedtime.com.au/wp-content/uploads/product-images_1280x720_cleo.jpg',
    ratings: 4.7,
    reviews: [
      {
        user: 'James Thompson',
        comment: 'Elegant and comfortable. The linen fabric is high quality.',
        rating: 5,
      },
    ],
    tags: ['bed', 'bedroom', 'upholstered', 'luxury'],
    shippingInfo: { weight: 85.7, deliveryTime: '14-21 days' },
    warranty: '3 years',
    returnPolicy: '60-day return',
    style: 'Scandinavian',
  },
  {
    _id: '4n5o6p7q-8r9s-0t1u-2v3w-4x5y6z7a8b9c',
    name: 'Wall-Mounted Coat Rack',
    arrivalDate: '2023-12-28',
    price: 59.99,
    discount: null,
    stock: 30,
    description: 'Minimalist wall-mounted coat rack with brass hooks and oak shelf for entryway organization.',
    dimensions: { height: '30cm', width: '80cm', depth: '15cm' },
    size: 'small',
    material: 'oak & brass',
    category: 'Bedroom',
    status: [],
    colors: [
      {
        name: 'Natural Oak',
        hex: '#D2B48C',
        image: 'https://m.media-amazon.com/images/I/717ATIUgUBL._AC_UF350,350_QL80_.jpg',
      },
    ],
    image: 'https://m.media-amazon.com/images/I/717ATIUgUBL._AC_UF350,350_QL80_.jpg',
    ratings: 4.1,
    reviews: [
      {
        user: 'Olivia Martin',
        comment: 'Beautiful and functional. Perfect for our small entryway.',
        rating: 4,
      },
    ],
    tags: ['coat rack', 'entryway', 'wall-mounted', 'minimalist'],
    shippingInfo: { weight: 5.2, deliveryTime: '3-5 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Scandinavian',
  },
  {
    _id: '5o6p7q8r-9s0t-1u2v-3w4x-5y6z7a8b9c0d',
    name: 'Marble Side Table',
    arrivalDate: '2024-05-07',
    price: 249.99,
    discount: 10,
    stock: 11,
    description: 'Elegant side table with real marble top and gold-tone metal base for luxurious accents.',
    dimensions: { height: '55cm', width: '45cm', depth: '45cm' },
    size: 'small',
    material: 'marble & metal',
    category: 'Living Room',
    status: ['new arrival'],
    colors: [
      {
        name: 'Carrara Marble',
        hex: '#F0ECE1',
        image: 'https://www.lussostone.com/images/monet-arabescato-marble-side-table-380mm-p5885-34772_zoom.jpg',
      },
      {
        name: 'Black Marble',
        hex: '#0A0A0A',
        image:
          'https://res.cloudinary.com/kiansalout/image/upload/v1657420593/Mawrble/Products/Side%20Tables/T-Stone/ExtraS/TStone_ST_P_2x_lvepjq.webp',
      },
    ],
    image: 'https://www.lussostone.com/images/monet-arabescato-marble-side-table-380mm-p5885-34772_zoom.jpg',
    ratings: 4.5,
    reviews: [
      {
        user: 'Ethan Davis',
        comment: 'Stunning piece that elevates our living room decor.',
        rating: 5,
      },
    ],
    tags: ['side table', 'marble', 'luxury', 'living-room'],
    shippingInfo: { weight: 18.9, deliveryTime: '5-7 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '6p7q8r9s-0t1u-2v3w-4x5y-6z7a8b9c0d1e',
    name: 'Folding Bistro Set',
    arrivalDate: '2024-02-05',
    price: 149.99,
    discount: null,
    stock: 18,
    description: 'Compact folding bistro set perfect for balconies or small patios with weather-resistant materials.',
    dimensions: { height: '75cm', width: '60cm', depth: '60cm' },
    size: 'small',
    material: 'metal & plastic',
    category: 'Outdoor',
    status: [],
    colors: [
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://www.tofs.com/cdn/shop/files/10514011Rattaneffectbistroset2.jpg?v=1708153289',
      },
      {
        name: 'White',
        hex: '#FFFFFF',
        image: 'https://www.noaandnani.co.uk/cdn/shop/files/LucerneWhitewithprops-min_1.jpg?v=1715171109&width=800',
      },
    ],
    image: 'https://www.tofs.com/cdn/shop/files/10514011Rattaneffectbistroset2.jpg?v=1708153289',
    ratings: 4.0,
    reviews: [
      {
        user: 'Noah Wilson',
        comment: 'Perfect for our apartment balcony. Folds away easily when not in use.',
        rating: 4,
      },
    ],
    tags: ['bistro', 'outdoor', 'folding', 'compact'],
    shippingInfo: { weight: 15.8, deliveryTime: '5-7 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '7q8r9s0t-1u2v-3w4x-5y6z-7a8b9c0d1e2f',
    name: 'Velvet Dining Chairs',
    arrivalDate: '2024-04-12',
    price: 199.99,
    discount: 15,
    stock: 14,
    description: 'Set of 2 velvet upholstered dining chairs with gold-tone legs for elegant dining spaces.',
    dimensions: { height: '90cm', width: '50cm', depth: '55cm' },
    size: 'medium',
    material: 'velvet & metal',
    category: 'Dining',
    status: ['top seller'],
    colors: [
      {
        name: 'Emerald Green',
        hex: '#50C878',
        image:
          'https://i5.walmartimages.com/seo/WestinTrends-Wordford-Velvet-Dining-Chairs-Set-4-Modern-Wingback-Upholstered-Button-Tufted-Kitchen-Room-Solid-Wood-Legs-Pull-Ring-Green_7f3d1dd6-9fa1-4670-83aa-e3c3c4c9d248.b0e41b751ea3df7887aef9105a5165d1.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
      },
      {
        name: 'Blush Pink',
        hex: '#FFB6C1',
        image:
          'https://i5.walmartimages.com/seo/WestinTrends-Wordford-Velvet-Dining-Chairs-Set-4-Modern-Wingback-Upholstered-Button-Tufted-Kitchen-Room-Solid-Wood-Legs-Pull-Ring-Pink_0a56b9fb-11c2-4b72-b762-3cefa03f8c99.354786ed91c1c6677d58abe12a281b8a.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
      },
    ],
    image:
      'https://i5.walmartimages.com/seo/WestinTrends-Wordford-Velvet-Dining-Chairs-Set-4-Modern-Wingback-Upholstered-Button-Tufted-Kitchen-Room-Solid-Wood-Legs-Pull-Ring-Green_7f3d1dd6-9fa1-4670-83aa-e3c3c4c9d248.b0e41b751ea3df7887aef9105a5165d1.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
    ratings: 4.6,
    reviews: [
      {
        user: 'Ava Johnson',
        comment: 'Beautiful chairs that are surprisingly comfortable for long dinners.',
        rating: 5,
      },
    ],
    tags: ['dining chairs', 'velvet', 'elegant', 'set of 2'],
    shippingInfo: { weight: 24.7, deliveryTime: '7-10 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '8r9s0t1u-2v3w-4x5y-6z7a-8b9c0d1e2f3g',
    name: 'Industrial Bookshelf Lamp',
    arrivalDate: '2024-03-15',
    price: 129.99,
    discount: null,
    stock: 22,
    description: 'Adjustable arm lamp with industrial design perfect for reading nooks or desks.',
    dimensions: { height: '50cm', width: '30cm', depth: '20cm' },
    size: 'small',
    material: 'metal',
    category: 'Living Room',
    status: ['new arrival'],
    colors: [
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://vintiige.com/cdn/shop/products/product-image-453769162.jpg?v=1594279639',
      },
      {
        name: 'Copper',
        hex: '#B87333',
        image:
          'https://vintiige.com/cdn/shop/products/product-image-453769163_grande_541d2c66-83f4-48af-ac63-29fe3d70c64e.jpg?v=1594279639&width=416',
      },
    ],
    image: 'https://vintiige.com/cdn/shop/products/product-image-453769162.jpg?v=1594279639',
    ratings: 4.3,
    reviews: [
      {
        user: 'Liam Brown',
        comment: 'Great adjustable light for my reading corner. Very sturdy construction.',
        rating: 4,
      },
    ],
    tags: ['lamp', 'industrial', 'adjustable', 'reading'],
    shippingInfo: { weight: 6.8, deliveryTime: '3-5 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Industrial',
  },
  {
    _id: '9s0t1u2v-3w4x-5y6z-7a8b-9c0d1e2f3g4h',
    name: 'Wicker Storage Basket',
    arrivalDate: '2023-11-15',
    price: 49.99,
    discount: null,
    stock: 35,
    description: 'Handwoven wicker storage basket with leather handles for stylish organization.',
    dimensions: { height: '40cm', width: '50cm', depth: '30cm' },
    size: 'medium',
    material: 'wicker & leather',
    category: 'Bedroom',
    status: [],
    colors: [
      {
        name: 'Natural',
        hex: '#D2B48C',
        image:
          'https://www.thebasketcompany.com/images/rectangular-honey-rattan-deep-wicker-storage-baskets-p807-7907_zoom.jpg',
      },
    ],
    image:
      'https://www.thebasketcompany.com/images/rectangular-honey-rattan-deep-wicker-storage-baskets-p807-7907_zoom.jpg',
    ratings: 4.0,
    reviews: [
      {
        user: 'Sophie Martin',
        comment: 'Beautiful and holds all our living room blankets neatly.',
        rating: 4,
      },
    ],
    tags: ['basket', 'storage', 'wicker', 'organization'],
    shippingInfo: { weight: 3.5, deliveryTime: '3-5 days' },
    warranty: null,
    returnPolicy: '30-day return',
    style: 'Bohemian',
  },
  {
    _id: '0t1u2v3w-4x5y-6z7a-8b9c-0d1e2f3g4h5i',
    name: 'Modern Bar Cabinet',
    arrivalDate: '2024-04-18',
    price: 599.99,
    discount: 20,
    stock: 6,
    description: 'Sleek bar cabinet with glass shelves, interior lighting, and locking doors for stylish storage.',
    dimensions: { height: '120cm', width: '80cm', depth: '40cm' },
    size: 'large',
    material: 'wood & glass',
    category: 'Living Room',
    status: ['top seller'],
    colors: [
      {
        name: 'Walnut',
        hex: '#5C4033',
        image: 'https://m.media-amazon.com/images/I/71dotxyO7jL._AC_UF1000,1000_QL80_.jpg',
      },
      {
        name: 'White',
        hex: '#FFFFFF',
        image: 'https://belleze.com/cdn/shop/files/014-HG-43509-WS_01.jpg?v=1729560411&width=2048',
      },
    ],
    image: 'https://m.media-amazon.com/images/I/71dotxyO7jL._AC_UF1000,1000_QL80_.jpg',
    ratings: 4.7,
    reviews: [
      {
        user: 'Benjamin Lee',
        comment: 'Beautiful cabinet that displays our glassware perfectly with the interior lighting.',
        rating: 5,
      },
    ],
    tags: ['bar cabinet', 'storage', 'modern', 'living-room'],
    shippingInfo: { weight: 45.8, deliveryTime: '10-14 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '1u2v3w4x-5y6z-7a8b-9c0d-1e2f3g4h5i6j',
    name: 'Adjustable Laptop Stand',
    arrivalDate: '2024-01-05',
    price: 79.99,
    discount: null,
    stock: 28,
    description: 'Ergonomic laptop stand with 6 height adjustments and foldable design for portability.',
    dimensions: { height: '10-25cm', width: '35cm', depth: '25cm' },
    size: 'small',
    material: 'aluminum',
    category: 'Office Furniture',
    status: [],
    colors: [
      { name: 'Silver', hex: '#C0C0C0', image: 'https://m.media-amazon.com/images/I/61mxayC-eVL.jpg' },
      { name: 'Space Gray', hex: '#717378', image: 'https://m.media-amazon.com/images/I/51TZ+zZunKL.jpg' },
    ],
    image: 'https://m.media-amazon.com/images/I/61mxayC-eVL.jpg',
    ratings: 4.4,
    reviews: [
      {
        user: 'Daniel Kim',
        comment: 'Perfect for working from home. Helps with my posture significantly.',
        rating: 5,
      },
    ],
    tags: ['laptop stand', 'ergonomic', 'adjustable', 'office'],
    shippingInfo: { weight: 2.3, deliveryTime: '3-5 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '2v3w4x5y-6z7a-8b9c-0d1e-2f3g4h5i6j7k',
    name: 'Floating Wall Shelves',
    arrivalDate: '2024-02-18',
    price: 89.99,
    discount: 10,
    stock: 20,
    description: 'Set of 3 minimalist floating shelves with hidden brackets for clean display spaces.',
    dimensions: { height: '15cm', width: '60cm', depth: '20cm' },
    size: 'medium',
    material: 'solid wood',
    category: 'Living Room',
    status: [],
    colors: [
      { name: 'White', hex: '#FFFFFF', image: 'https://i.ebayimg.com/images/g/DPAAAOSwP6pk80T6/s-l400.png' },
      {
        name: 'Walnut',
        hex: '#5C4033',
        image:
          'https://i5.walmartimages.com/seo/Afuly-Rustic-Wood-Floating-Shelves-Wall-Mounted-Set-of-3-16In-Brown-Wall-Shelf-with-Metal-Brackets-Hanging-Shelf-Home-Decor-Storage_ac958c23-b147-42e4-abf3-a5e52b9f9be7.81d1c8bb0bc4479c3a31d5046419d182.jpeg',
      },
    ],
    image: 'https://i.ebayimg.com/images/g/DPAAAOSwP6pk80T6/s-l400.png',
    ratings: 4.2,
    reviews: [
      {
        user: 'Emma Wilson',
        comment: 'Easy to install and perfect for displaying our photos and plants.',
        rating: 4,
      },
    ],
    tags: ['shelves', 'wall-mounted', 'minimalist', 'storage'],
    shippingInfo: { weight: 12.5, deliveryTime: '5-7 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Scandinavian',
  },
  {
    _id: '3w4x5y6z-7a8b-9c0d-1e2f-3g4h5i6j7k8l',
    name: 'Leather Office Chair',
    arrivalDate: '2023-12-08',
    price: 399.99,
    discount: 15,
    stock: 9,
    description: 'Executive leather office chair with adjustable lumbar support and tilt mechanism.',
    dimensions: { height: '120-135cm', width: '65cm', depth: '70cm' },
    size: 'medium',
    material: 'genuine leather',
    category: 'Office Furniture',
    status: ['top seller'],
    colors: [
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://m.media-amazon.com/images/I/71hePpVKObL._AC_UF1000,1000_QL80_.jpg',
      },
      { name: 'Brown', hex: '#5C4033', image: 'https://m.media-amazon.com/images/I/71heil7CimL.jpg' },
    ],
    image: 'https://m.media-amazon.com/images/I/71hePpVKObL._AC_UF1000,1000_QL80_.jpg',
    ratings: 4.5,
    reviews: [
      {
        user: 'Michael Johnson',
        comment: 'Extremely comfortable for long work hours. The leather is high quality.',
        rating: 5,
      },
    ],
    tags: ['office chair', 'ergonomic', 'executive', 'leather'],
    shippingInfo: { weight: 28.7, deliveryTime: '7-10 days' },
    warranty: '3 years',
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '4x5y6z7a-8b9c-0d1e-2f3g-4h5i6j7k8l9m',
    name: 'Round Mirror with Shelf',
    arrivalDate: '2024-03-28',
    price: 179.99,
    discount: null,
    stock: 12,
    description: 'Decorative round mirror with built-in wooden shelf for entryway or bedroom decor.',
    dimensions: { height: '80cm', width: '80cm', depth: '15cm' },
    size: 'medium',
    material: 'wood & glass',
    category: 'Bedroom',
    status: ['new arrival'],
    colors: [
      { name: 'Walnut', hex: '#5C4033', image: 'https://cb2.scene7.com/is/image/CB2/PerchRndMrrrWShlf36SHF18' },
      {
        name: 'White',
        hex: '#FFFFFF',
        image: 'https://img.tapwarehouse.com/products/c/d/a/8/cda8550c8aeebd53aa70e5c44d7caaa9591e0397_dockland010.jpg',
      },
    ],
    image: 'https://cb2.scene7.com/is/image/CB2/PerchRndMrrrWShlf36SHF18',
    ratings: 4.3,
    reviews: [
      {
        user: 'Olivia Davis',
        comment: 'Beautiful mirror that adds light to our entryway. The shelf is practical too.',
        rating: 4,
      },
    ],
    tags: ['mirror', 'decor', 'entryway', 'shelf'],
    shippingInfo: { weight: 15.8, deliveryTime: '5-7 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '5y6z7a8b-9c0d-1e2f-3g4h-5i6j7k8l9m0n',
    name: 'Outdoor Dining Set',
    arrivalDate: '2024-04-22',
    price: 899.99,
    discount: 25,
    stock: 4,
    description: 'Complete 6-piece outdoor dining set with weather-resistant cushions and umbrella hole.',
    dimensions: { height: '75cm', width: '150cm', depth: '90cm' },
    size: 'large',
    material: 'rattan & metal',
    category: 'Outdoor',
    status: ['top seller'],
    colors: [
      {
        name: 'Gray',
        hex: '#808080',
        image:
          'https://assets.wfcdn.com/im/73929836/compr-r85/2705/270521247/akiva-6-person-round-outdoor-dining-set-with-cushions.jpg',
      },
      {
        name: 'Taupe',
        hex: '#483C32',
        image:
          'https://assets.roomstogo.com/product/bay-terrace-gray-wicker-5-pc-48-in-round-outdoor-dining-set_7521354P_image-3-2?cache-id=47cdc5ebd338b818ac3d396246f52bda&w=1920&q=80',
      },
    ],
    image:
      'https://ak1.ostkcdn.com/images/products/is/images/direct/fd72d0d67c7a9f46b805b000e8a5a07b29a67b74/Nadine-5-pc.-Teak-Dining-Set-with-Rope-Chairs.jpg?impolicy=medium',
    ratings: 4.6,
    reviews: [
      {
        user: 'William Taylor',
        comment: 'Perfect for our patio. Withstood several rainstorms without damage.',
        rating: 5,
      },
    ],
    tags: ['outdoor', 'dining set', 'patio', 'weather-resistant'],
    shippingInfo: { weight: 120.5, deliveryTime: '14-21 days' },
    warranty: '2 years',
    returnPolicy: '60-day return',
    style: 'Bohemian',
  },
  {
    _id: '6z7a8b9c-0d1e-2f3g-4h5i-6j7k8l9m0n1o',
    name: 'Velvet Accent Chair',
    arrivalDate: '2024-02-25',
    price: 349.99,
    discount: null,
    stock: 8,
    description: 'Plush velvet accent chair with tapered legs and comfortable seat cushion.',
    dimensions: { height: '85cm', width: '70cm', depth: '75cm' },
    size: 'medium',
    material: 'velvet & wood',
    category: 'Living Room',
    status: [],
    colors: [
      {
        name: 'Sapphire Blue',
        hex: '#0F52BA',
        image:
          'https://i5.walmartimages.com/seo/Mid-Century-Accent-Chair-Button-Tufted-Upholstered-Sofa-Chairs-Modern-Velvet-Ergonomic-Armchair-for-Living-Room-Bedroom-Reading-Teal_fbcaa1d7-9ce5-46db-a549-d8d4eaa315f2.63afc78a0f3490db53c336dd2e0ca9a6.jpeg',
      },
      {
        name: 'Mustard Yellow',
        hex: '#FFDB58',
        image:
          '/https://ak1.ostkcdn.com/images/products/is/images/direct/0f7a70c31ad17e39deac53d4bcf2cc957ee64c2c/Accent-Chair%2C-Mid-Century-Modern-Comfy-Reading-Chair-Upholstered-Velvet-Armchair-for-Bedroom%2C-Living-Room%2CYellow.jpg?impolicy=medium',
      },
    ],
    image:
      'https://i5.walmartimages.com/seo/Mid-Century-Accent-Chair-Button-Tufted-Upholstered-Sofa-Chairs-Modern-Velvet-Ergonomic-Armchair-for-Living-Room-Bedroom-Reading-Teal_fbcaa1d7-9ce5-46db-a549-d8d4eaa315f2.63afc78a0f3490db53c336dd2e0ca9a6.jpeg',
    ratings: 4.4,
    reviews: [
      {
        user: 'Sophia Wilson',
        comment: 'Beautiful pop of color in our living room. Very comfortable too.',
        rating: 4,
      },
    ],
    tags: ['accent chair', 'velvet', 'living-room', 'decor'],
    shippingInfo: { weight: 22.6, deliveryTime: '7-10 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Traditional',
  },
  {
    _id: '7a8b9c0d-1e2f-3g4h-5i6j-7k8l9m0n1o2p',
    name: 'Bunk Bed with Desk',
    arrivalDate: '2024-05-09',
    price: 799.99,
    discount: 15,
    stock: 5,
    description: 'Space-saving bunk bed with built-in desk and storage drawers for kids or small spaces.',
    dimensions: { height: '180cm', width: '150cm', depth: '210cm' },
    size: 'large',
    material: 'solid wood',
    category: 'Bedroom',
    status: ['new arrival'],
    colors: [
      { name: 'White', hex: '#FFFFFF', image: 'https://m.media-amazon.com/images/I/61SAO9cs+dL._AC_SL1000_.jpg' },
      {
        name: 'Natural',
        hex: '#D2B48C',
        image: 'https://i.etsystatic.com/23425312/r/il/96065a/6345564770/il_570xN.6345564770_6w4s.jpg',
      },
    ],
    image: 'https://m.media-amazon.com/images/I/61SAO9cs+dL._AC_SL1000_.jpg',
    ratings: 4.5,
    reviews: [
      {
        user: 'David Miller',
        comment: 'Perfect for my two boys. The desk and storage are great space savers.',
        rating: 5,
      },
    ],
    tags: ['bunk bed', 'kids', 'space-saving', 'desk'],
    shippingInfo: { weight: 95.7, deliveryTime: '14-21 days' },
    warranty: '3 years',
    returnPolicy: '60-day return',
    style: 'Modern',
  },
  {
    _id: '8b9c0d1e-2f3g-4h5i-6j7k-8l9m0n1o2p3q',
    name: 'Glass Display Coffee Table',
    arrivalDate: '2024-03-08',
    price: 499.99,
    discount: null,
    stock: 7,
    description: 'Modern coffee table with glass top and illuminated display compartment for collectibles.',
    dimensions: { height: '45cm', width: '120cm', depth: '60cm' },
    size: 'medium',
    material: 'glass & metal',
    category: 'Living Room',
    status: [],
    colors: [
      {
        name: 'Chrome',
        hex: '#E8E8E8',
        image:
          'https://preview.redd.it/my-attempt-at-a-millennium-falcon-coffee-table-display-case-v0-5hmuvtglkb3a1.jpg?width=1080&crop=smart&auto=webp&s=69e140826f628b6d77039be9b914a30c04d4b8a4',
      },
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://www.showfront.com.au/collectors/media/wysiwyg/Blog/lego-cabinets-1-min.jpg',
      },
    ],
    image:
      'https://preview.redd.it/my-attempt-at-a-millennium-falcon-coffee-table-display-case-v0-5hmuvtglkb3a1.jpg?width=1080&crop=smart&auto=webp&s=69e140826f628b6d77039be9b914a30c04d4b8a4',
    ratings: 4.3,
    reviews: [
      {
        user: 'Emma Thompson',
        comment: 'Beautiful table that showcases our collectibles perfectly with the lighting.',
        rating: 4,
      },
    ],
    tags: ['coffee table', 'modern', 'display', 'living-room'],
    shippingInfo: { weight: 35.8, deliveryTime: '7-10 days' },
    warranty: '2 years',
    returnPolicy: '30-day return',
    style: 'Modern',
  },
  {
    _id: '9c0d1e2f-3g4h-5i6j-7k8l-9m0n1o2p3q4r',
    name: 'Farmhouse Dining Table',
    arrivalDate: '2024-01-12',
    price: 899.99,
    discount: 20,
    stock: 3,
    description: 'Rustic farmhouse dining table with distressed finish and sturdy construction seats 8 comfortably.',
    dimensions: { height: '75cm', width: '220cm', depth: '100cm' },
    size: 'large',
    material: 'reclaimed wood',
    category: 'Dining',
    status: ['top seller'],
    colors: [
      {
        name: 'Weathered Gray',
        hex: '#808080',
        image: 'https://thefarmhousefinds.com/cdn/shop/products/il_fullxfull.1798949949_888o.jpg?v=1691589255',
      },
      {
        name: 'Barn Red',
        hex: '#7C0A02',
        image:
          'https://edwardgeorgelondon.com/wp-content/uploads/2024/09/Rustic-modern-Italian-farmhouse-dining-room-with-terracotta-floors-crystal-chandelier-velvet-seating-and-fresh-flowers-683x1024.webp',
      },
    ],
    image: 'https://thefarmhousefinds.com/cdn/shop/products/il_fullxfull.1798949949_888o.jpg?v=1691589255',
    ratings: 4.8,
    reviews: [
      {
        user: 'James Wilson',
        comment: "Stunning table that's the centerpiece of our dining room. Very sturdy.",
        rating: 5,
      },
    ],
    tags: ['dining table', 'farmhouse', 'rustic', 'reclaimed'],
    shippingInfo: { weight: 110.5, deliveryTime: '14-21 days' },
    warranty: '5 years',
    returnPolicy: '60-day return',
    style: 'Traditional',
  },
  {
    _id: '0d1e2f3g-4h5i-6j7k-8l9m-0n1o2p3q4r5s',
    name: 'Memory Foam Mattress',
    arrivalDate: '2024-05-15',
    price: 699.99,
    discount: 30,
    stock: 10,
    description: 'Premium gel-infused memory foam mattress with cooling technology for comfortable sleep.',
    dimensions: { height: '25cm', width: '150cm', depth: '200cm' },
    size: 'large',
    material: 'memory foam',
    category: 'Bedroom',
    status: ['new arrival'],
    colors: [
      {
        name: 'White',
        hex: '#FFFFFF',
        image:
          'https://i5.walmartimages.com/seo/Zinus-Spa-Sensations-Serenity-10-Twin-Medium-Tight-Top-Memory-Foam-Mattress_f23a461a-175a-408c-abba-4c7d088ca5e4.0b37454de28be56b864ad4492573a8c8.jpeg?odnHeight=320&odnWidth=320&odnBg=FFFFFF',
      },
    ],
    image:
      'https://i5.walmartimages.com/seo/Zinus-Spa-Sensations-Serenity-10-Twin-Medium-Tight-Top-Memory-Foam-Mattress_f23a461a-175a-408c-abba-4c7d088ca5e4.0b37454de28be56b864ad4492573a8c8.jpeg?odnHeight=320&odnWidth=320&odnBg=FFFFFF',
    ratings: 4.7,
    reviews: [
      {
        user: 'Sophia Chen',
        comment: "Best sleep I've had in years. The cooling technology really works.",
        rating: 5,
      },
    ],
    tags: ['mattress', 'memory foam', 'bedroom', 'cooling'],
    shippingInfo: { weight: 45.8, deliveryTime: '7-10 days' },
    warranty: '10 years',
    returnPolicy: '100-night trial',
    style: 'Modern',
  },
  {
    _id: '1e2f3g4h-5i6j-7k8l-9m0n-1o2p3q4r5s6t',
    name: 'Ceramic Table Lamp',
    arrivalDate: '2023-12-22',
    price: 89.99,
    discount: null,
    stock: 25,
    description: 'Handcrafted ceramic table lamp with linen shade for warm ambient lighting.',
    dimensions: { height: '60cm', width: '25cm', depth: '25cm' },
    size: 'small',
    material: 'ceramic & linen',
    category: 'Living Room',
    status: [],
    colors: [
      {
        name: 'Terracotta',
        hex: '#E2725B',
        image: 'https://oblist.com/cdn/shop/files/mc_Z1134Hd3To.jpg?v=1718199821&width=2744',
      },
      {
        name: 'Oatmeal',
        hex: '#EDE6D6',
        image:
          'https://static.zara.net/assets/public/2728/4acd/4306488ba71c/38d74144f948/46311047682-e2/46311047682-e2.jpg?ts=1716881724467',
      },
    ],
    image: 'https://oblist.com/cdn/shop/files/mc_Z1134Hd3To.jpg?v=1718199821&width=2744',
    ratings: 4.2,
    reviews: [
      {
        user: 'Noah Davis',
        comment: 'Beautiful lamp that gives off the perfect warm glow.',
        rating: 4,
      },
    ],
    tags: ['lamp', 'ceramic', 'lighting', 'decor'],
    shippingInfo: { weight: 5.7, deliveryTime: '3-5 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Bohemian',
  },
  {
    _id: '2f3g4h5i-6j7k-8l9m-0n1o-2p3q4r5s6t7u',
    name: 'Wall-Mounted Bike Rack',
    arrivalDate: '2024-02-08',
    price: 69.99,
    discount: null,
    stock: 18,
    description: 'Space-saving bike rack that mounts to wall or ceiling to keep bikes organized.',
    dimensions: { height: '15cm', width: '80cm', depth: '30cm' },
    size: 'small',
    material: 'steel',
    category: 'Outdoor',
    status: [],
    colors: [
      {
        name: 'Black',
        hex: '#000000',
        image: 'https://g-force.com.au/wp-content/uploads/2021/03/Race-white-1-e1616119177599.jpeg',
      },
    ],
    image: 'https://g-force.com.au/wp-content/uploads/2021/03/Race-white-1-e1616119177599.jpeg',
    ratings: 4.1,
    reviews: [
      {
        user: 'Liam Wilson',
        comment: 'Perfect solution for our small garage. Holds two bikes securely.',
        rating: 4,
      },
    ],
    tags: ['bike rack', 'storage', 'wall-mounted', 'garage'],
    shippingInfo: { weight: 8.5, deliveryTime: '5-7 days' },
    warranty: '1 year',
    returnPolicy: '30-day return',
    style: 'Industrial',
  },
];

export type ApplicationImageDataType = (typeof dummyData)[0];
